export const newlisttest = [
    {
        //changed digit in order number
        "OrderNumber": 11314789,
        "CustomerNumber": 98941,
        "CustomerName": "CASSELLA, EJ",
        "StockShipped": "*HOOKUPREFRIG1",
        "Description1": "HOOKUP REFRIGERATOR",
        "QuantitytoShip": 1,
        "Salesperson": 304,
        "ShippingDate": 45278,
        "ShiptoAddress1": "1012 E TOLEDO ST",
        "ShiptoCity": "BELLINGHAM",
        "ShiptoState": "WA",
        "ShiptoZipCode": 98229
    },
    {
        //changed to lg refer instead of beko
        "OrderNumber": 11314787,
        "CustomerNumber": 98941,
        "CustomerName": "CASSELLA, EJ",
        "StockShipped": "LFCC44567W",
        "Description1": "LG REFER",
        "QuantitytoShip": " EJ\"",
        "Salesperson": "*DELIVERY",
        "ShippingDate": "DELIVERY CHARGE",
        "ShiptoAddress1": 1,
        "ShiptoAddress2": 304,
        "ShiptoCity": 45278,
        "ShiptoState": "1012 E TOLEDO ST",
        "Category": "BELLINGHAM",
        "ServiceTime": "WA",
        "__EMPTY": 98229
    },
    {
        "OrderNumber": 11316872,
        "CustomerNumber": 128950,
        "CustomerName": "COLLINS, MISHA",
        "StockShipped": "LSIS6338F",
        "Description1": "\"LG Studio 30\\\" Slide-In\",1,312,45278,\"1425 AUSTIN ST\",\"\",\"BELLINGHAM\",\"WA\",\"98229\",\"\",\"\"\n11316872,128950,\"COLLINS",
        "QuantitytoShip": " MISHA\"",
        "Salesperson": 14036,
        "ShippingDate": "5 YEAR PARTS/LABOR WARRANTY",
        "ShiptoAddress1": 1,
        "ShiptoAddress2": 312,
        "ShiptoCity": 45278,
        "ShiptoState": "1425 AUSTIN ST",
        "Category": "BELLINGHAM",
        "ServiceTime": "WA",
        "__EMPTY": 98229
    },
    {
        "OrderNumber": 11316872,
        "CustomerNumber": 128950,
        "CustomerName": "COLLINS, MISHA",
        "StockShipped": "HBC143ESS",
        "Description1": "\"Best 43\\\" Ceiling Mounted Range\",1,312,45278,\"1425 AUSTIN ST\",\"\",\"BELLINGHAM\",\"WA\",\"98229\",\"\",\"\"\n11316872,128950,\"COLLINS",
        "QuantitytoShip": " MISHA\"",
        "Salesperson": 14036,
        "ShippingDate": "5 YEAR PARTS/LABOR WARRANTY",
        "ShiptoAddress1": 1,
        "ShiptoAddress2": 312,
        "ShiptoCity": 45278,
        "ShiptoState": "1425 AUSTIN ST",
        "Category": "BELLINGHAM",
        "ServiceTime": "WA",
        "__EMPTY": 98229
    },
    {
        "OrderNumber": 11316872,
        "CustomerNumber": 128950,
        "CustomerName": "COLLINS, MISHA",
        "StockShipped": "ILB6",
        "Description1": "BEST 600CFM INLINE BLOWER",
        "QuantitytoShip": 1,
        "Salesperson": 312,
        "ShippingDate": 45278,
        "ShiptoAddress1": "1425 AUSTIN ST",
        "ShiptoCity": "BELLINGHAM",
        "ShiptoState": "WA",
        "ShiptoZipCode": 98229
    },
    {
        "OrderNumber": 11316872,
        "CustomerNumber": 128950,
        "CustomerName": "COLLINS, MISHA",
        "StockShipped": "*DELIVERY",
        "Description1": "DELIVERY CHARGE",
        "QuantitytoShip": 1,
        "Salesperson": 312,
        "ShippingDate": 45278,
        "ShiptoAddress1": "1425 AUSTIN ST",
        "ShiptoCity": "BELLINGHAM",
        "ShiptoState": "WA",
        "ShiptoZipCode": 98229
    },
    {
        "OrderNumber": 11316872,
        "CustomerNumber": 128950,
        "CustomerName": "COLLINS, MISHA",
        "StockShipped": "*CORD",
        "Description1": "RANGE OR DRYER CORD",
        "QuantitytoShip": 1,
        "Salesperson": 312,
        "ShippingDate": 45278,
        "ShiptoAddress1": "1425 AUSTIN ST",
        "ShiptoCity": "BELLINGHAM",
        "ShiptoState": "WA",
        "ShiptoZipCode": 98229
    },
    {
        "OrderNumber": 11316872,
        "CustomerNumber": 128950,
        "CustomerName": "COLLINS, MISHA",
        "StockShipped": "*DISPOSAL",
        "Description1": "APPLIANCE UNINSTALLED AND",
        "QuantitytoShip": 1,
        "Salesperson": 312,
        "ShippingDate": 45278,
        "ShiptoAddress1": "1425 AUSTIN ST",
        "ShiptoCity": "BELLINGHAM",
        "ShiptoState": "WA",
        "ShiptoZipCode": 98229
    },
    {
        "OrderNumber": 11316872,
        "CustomerNumber": 128950,
        "CustomerName": "COLLINS, MISHA",
        "StockShipped": "*INSTALLHLINER",
        "Description1": "\"INSTALL HOOD LINER UP TO 36\\\"\",1,312,45278,\"1425 AUSTIN ST\",\"\",\"BELLINGHAM\",\"WA\",\"98229\",\"\",\"\"\n11316872,128950,\"COLLINS",
        "QuantitytoShip": " MISHA\"",
        "Salesperson": "JES1657DMWW",
        "ShippingDate": "GE 1.6 cu ft Countertop",
        "ShiptoAddress1": 1,
        "ShiptoAddress2": 312,
        "ShiptoCity": 45278,
        "ShiptoState": "1425 AUSTIN ST",
        "Category": "BELLINGHAM",
        "ServiceTime": "WA",
        "__EMPTY": 98229
    },
    {
        "OrderNumber": 11316872,
        "CustomerNumber": 128950,
        "CustomerName": "COLLINS, MISHA",
        "StockShipped": "*DELIVERY",
        "Description1": "DELIVERY CHARGE",
        "QuantitytoShip": 1,
        "Salesperson": 312,
        "ShippingDate": 45278,
        "ShiptoAddress1": "1425 AUSTIN ST",
        "ShiptoCity": "BELLINGHAM",
        "ShiptoState": "WA",
        "ShiptoZipCode": 98229
    },
    {
        "OrderNumber": 11317412,
        "CustomerNumber": 141943,
        "CustomerName": "LOVE, LISA",
        "StockShipped": "GRSC2352AF",
        "Description1": "\"Frigidaire Gallery 36\\\" 22.3\",1,329,45278,\"5626 ELM COURT\",\"\",\"FERNDALE\",\"WA\",\"98248\",\"REF\",\"\"\n11317412,141943,\"LOVE",
        "QuantitytoShip": " LISA\"",
        "Salesperson": "GCFE3060BF",
        "ShippingDate": "\"Frigidaire Gallery 30\\\"\",1,329,45278,\"5626 ELM COURT\",\"\",\"FERNDALE\",\"WA\",\"98248\",\"\",\"\"\n11317412,141943,\"LOVE",
        "ShiptoAddress1": " LISA\"",
        "ShiptoAddress2": "JVW5301SJSS",
        "ShiptoCity": "\"GE 30\\\" Wall Mount Chimney\",1,329,45278,\"5626 ELM COURT\",\"\",\"FERNDALE\",\"WA\",\"98248\",\"RAH\",\"\"\n11317412,141943,\"LOVE",
        "ShiptoState": " LISA\"",
        "ShiptoZipCode": "GDPH4515AF",
        "Category": "\"Frigidaire Gallery 24\\\"\",1,329,45278,\"5626 ELM COURT\",\"\",\"FERNDALE\",\"WA\",\"98248\",\"\",\"\"\n11317412,141943,\"LOVE",
        "ServiceTime": " LISA\"",
        "__EMPTY": "FGBC5334VS",
        "__EMPTY_1": "Frigidaire 5.3 cu ft Built In",
        "__EMPTY_2": 1,
        "__EMPTY_3": 329,
        "__EMPTY_4": 45278,
        "__EMPTY_5": "5626 ELM COURT",
        "__EMPTY_7": "FERNDALE",
        "__EMPTY_8": "WA",
        "__EMPTY_9": 98248
    },
    {
        "OrderNumber": 11317412,
        "CustomerNumber": 141943,
        "CustomerName": "LOVE, LISA",
        "StockShipped": "*ESP",
        "Description1": "CUSTOMER DECLINED EXT WARRANTY",
        "QuantitytoShip": 1,
        "Salesperson": 329,
        "ShippingDate": 45278,
        "ShiptoAddress1": "5626 ELM COURT",
        "ShiptoCity": "FERNDALE",
        "ShiptoState": "WA",
        "ShiptoZipCode": 98248
    },
    {
        "OrderNumber": 11317412,
        "CustomerNumber": 141943,
        "CustomerName": "LOVE, LISA",
        "StockShipped": "*DELIVERY",
        "Description1": "DELIVERY CHARGE",
        "QuantitytoShip": 1,
        "Salesperson": 329,
        "ShippingDate": 45278,
        "ShiptoAddress1": "5626 ELM COURT",
        "ShiptoCity": "FERNDALE",
        "ShiptoState": "WA",
        "ShiptoZipCode": 98248
    },
    {
        "OrderNumber": 11320648,
        "CustomerNumber": 60916,
        "CustomerName": "BECK, ALICIA & RICK",
        "StockShipped": "RF203QDUVX1",
        "Description1": "\"Fisher Paykel Quad Door 36\\\"\",1,329,45278,\"4193 SALTSPRING DR\",\"\",\"FERNDALE\",\"WA\",\"98248\",\"REF\",60\n11320648,60916,\"BECK",
        "QuantitytoShip": " ALICIA & RICK\"",
        "Salesperson": 14036,
        "ShippingDate": "5 YEAR PARTS/LABOR WARRANTY",
        "ShiptoAddress1": 1,
        "ShiptoAddress2": 329,
        "ShiptoCity": 45278,
        "ShiptoState": "4193 SALTSPRING DR",
        "Category": "FERNDALE",
        "ServiceTime": "WA",
        "__EMPTY": 98248
    },
    {
        "OrderNumber": 11320648,
        "CustomerNumber": 60916,
        "CustomerName": "BECK, ALICIA & RICK",
        "StockShipped": "*HOOKUPREFRIG1",
        "Description1": "HOOKUP REFRIGERATOR",
        "QuantitytoShip": 1,
        "Salesperson": 329,
        "ShippingDate": 45278,
        "ShiptoAddress1": "4193 SALTSPRING DR",
        "ShiptoCity": "FERNDALE",
        "ShiptoState": "WA",
        "ShiptoZipCode": 98248
    },
    {
        "OrderNumber": 11320648,
        "CustomerNumber": 60916,
        "CustomerName": "BECK, ALICIA & RICK",
        "StockShipped": "*HAULAWAY",
        "Description1": "APPL CONTAINING REFRIGERANT",
        "QuantitytoShip": 1,
        "Salesperson": 329,
        "ShippingDate": 45278,
        "ShiptoAddress1": "4193 SALTSPRING DR",
        "ShiptoCity": "FERNDALE",
        "ShiptoState": "WA",
        "ShiptoZipCode": 98248
    },
    {
        "OrderNumber": 11320648,
        "CustomerNumber": 60916,
        "CustomerName": "BECK, ALICIA & RICK",
        "StockShipped": "*DELIVERY",
        "Description1": "DELIVERY CHARGE",
        "QuantitytoShip": 1,
        "Salesperson": 329,
        "ShippingDate": 45278,
        "ShiptoAddress1": "4193 SALTSPRING DR",
        "ShiptoCity": "FERNDALE",
        "ShiptoState": "WA",
        "ShiptoZipCode": 98248
    },
    {
        "OrderNumber": 11320960,
        "CustomerNumber": 186288,
        "CustomerName": "TOPOR, JANUSZ",
        "StockShipped": "*ESP",
        "Description1": "CUSTOMER DECLINED EXT WARRANTY",
        "QuantitytoShip": 1,
        "Salesperson": 335,
        "ShippingDate": 45278,
        "ShiptoAddress1": "3965 LOOMIS TRAIL RD",
        "ShiptoCity": "BLAINE",
        "ShiptoState": "WA",
        "ShiptoZipCode": 98230
    },
    {
        "OrderNumber": 11320960,
        "CustomerNumber": 186288,
        "CustomerName": "TOPOR, JANUSZ",
        "StockShipped": "528648-51",
        "Description1": "QUEEN Sealy Banstead Plush Tight",
        "QuantitytoShip": 1,
        "Salesperson": 335,
        "ShippingDate": 45278,
        "ShiptoAddress1": "3965 LOOMIS TRAIL RD",
        "ShiptoCity": "BLAINE",
        "ShiptoState": "WA",
        "ShiptoZipCode": 98230,
        "Category": "MAT"
    },
    {
        "OrderNumber": 11320960,
        "CustomerNumber": 186288,
        "CustomerName": "TOPOR, JANUSZ",
        "StockShipped": "528649-51",
        "Description1": "Sealy Banstead Plush Pillow",
        "QuantitytoShip": 1,
        "Salesperson": 335,
        "ShippingDate": 45278,
        "ShiptoAddress1": "3965 LOOMIS TRAIL RD",
        "ShiptoCity": "BLAINE",
        "ShiptoState": "WA",
        "ShiptoZipCode": 98230,
        "Category": "MAT"
    },
    {
        "OrderNumber": 11320960,
        "CustomerNumber": 186288,
        "CustomerName": "TOPOR, JANUSZ",
        "StockShipped": "*FREEDELIVERY",
        "Description1": "FREE DELIVERY TO HOME",
        "QuantitytoShip": 1,
        "Salesperson": 335,
        "ShippingDate": 45278,
        "ShiptoAddress1": "3965 LOOMIS TRAIL RD",
        "ShiptoCity": "BLAINE",
        "ShiptoState": "WA",
        "ShiptoZipCode": 98230
    },
    {
        "OrderNumber": 11321088,
        "CustomerNumber": 46344,
        "CustomerName": "BEACON MANOR APARTMENTS",
        "StockShipped": "NED4655EW",
        "Description1": "Amana 6.5 cu ft Dryer",
        "QuantitytoShip": 1,
        "Salesperson": 301,
        "ShippingDate": 45278,
        "ShiptoAddress1": "2308 DOUGLAS RD #301",
        "ShiptoAddress2": "DENAI 360-441-5886",
        "ShiptoCity": "FERNDALE",
        "ShiptoState": "WA",
        "ShiptoZipCode": 98248,
        "Category": "DRY",
        "ServiceTime": 45
    },
    {
        "OrderNumber": 11321088,
        "CustomerNumber": 46344,
        "CustomerName": "BEACON MANOR APARTMENTS",
        "StockShipped": "*DELIVERY",
        "Description1": "DELIVERY CHARGE",
        "QuantitytoShip": 1,
        "Salesperson": 301,
        "ShippingDate": 45278,
        "ShiptoAddress1": "2308 DOUGLAS RD #301",
        "ShiptoAddress2": "DENAI 360-441-5886",
        "ShiptoCity": "FERNDALE",
        "ShiptoState": "WA",
        "ShiptoZipCode": 98248
    },
    {
        "OrderNumber": 11321088,
        "CustomerNumber": 46344,
        "CustomerName": "BEACON MANOR APARTMENTS",
        "StockShipped": "*DISPOSAL",
        "Description1": "APPLIANCE UNINSTALLED AND",
        "QuantitytoShip": 1,
        "Salesperson": 301,
        "ShippingDate": 45278,
        "ShiptoAddress1": "2308 DOUGLAS RD #301",
        "ShiptoAddress2": "DENAI 360-441-5886",
        "ShiptoCity": "FERNDALE",
        "ShiptoState": "WA",
        "ShiptoZipCode": 98248
    },
    {
        "OrderNumber": 11321090,
        "CustomerNumber": 183714,
        "CustomerName": "CHUCKANUT PM & REALTY INC.",
        "StockShipped": "WET4024HW",
        "Description1": "Whirlpool 24\\\" Electric Laundry\",1,301,45278,\"2000 KNOX AVE #1\",\",\"BELLINGHAM\",\"WA\",\"98225\",\"COM\",45\n11321090,183714,\"CHUCKANUT PM & REALTY INC.\",\"*DELIVERY\",\"DELIVERY CHARGE\",1,301,45278,\"2000 KNOX AVE #1\",\",\"BELLINGHAM\",\"WA\",\"98225\",\",\"\n11321090,183714,\"CHUCKANUT PM & REALTY INC.\",\"*DISPOSAL\",\"APPLIANCE UNINSTALLED AND\",1,301,45278,\"2000 KNOX AVE #1\",\",\"BELLINGHAM\",\"WA\",\"98225\",\",\"\n11321092,168358,\"SAMISH COMMONS\",\"WM3400CW\",\"LG 27\\\" Front Load Washer",
        "QuantitytoShip": 1,
        "Salesperson": 301,
        "ShippingDate": 45278,
        "ShiptoAddress1": "1000 OTIS ST #A-102",
        "ShiptoAddress2": "P/U KEYS AT CCM SHOP",
        "ShiptoCity": "BELLINGHAM",
        "ShiptoState": "WA",
        "ShiptoZipCode": 98225,
        "Category": "WAS",
        "ServiceTime": 30
    },
    {
        "OrderNumber": 11321092,
        "CustomerNumber": 168358,
        "CustomerName": "SAMISH COMMONS",
        "StockShipped": 14035,
        "Description1": "5 YEAR PARTS/LABOR WARRANTY",
        "QuantitytoShip": 1,
        "Salesperson": 301,
        "ShippingDate": 45278,
        "ShiptoAddress1": "1000 OTIS ST #A-102",
        "ShiptoAddress2": "P/U KEYS AT CCM SHOP",
        "ShiptoCity": "BELLINGHAM",
        "ShiptoState": "WA",
        "ShiptoZipCode": 98225
    },
    {
        "OrderNumber": 11321092,
        "CustomerNumber": 168358,
        "CustomerName": "SAMISH COMMONS",
        "StockShipped": "DLE3400W",
        "Description1": "LG 27\\\" Electric Dryer\",1,301,45278,\"1000 OTIS ST #A-102\",\"P/U KEYS AT CCM SHOP\",\"BELLINGHAM\",\"WA\",\"98225\",\"DRY\",45\n11321092,168358,\"SAMISH COMMONS\",\"014035\",\"5 YEAR PARTS/LABOR WARRANTY\",1,301,45278,\"1000 OTIS ST #A-102\",\"P/U KEYS AT CCM SHOP\",\"BELLINGHAM\",\"WA\",\"98225\",\",\"\n11321092,168358,\"SAMISH COMMONS\",\"KSTK4\",\"LG Stacking Kit for 27\\\" Wide",
        "QuantitytoShip": 1,
        "Salesperson": 301,
        "ShippingDate": 45278,
        "ShiptoAddress1": "1000 OTIS ST #A-102",
        "ShiptoAddress2": "P/U KEYS AT CCM SHOP",
        "ShiptoCity": "BELLINGHAM",
        "ShiptoState": "WA",
        "ShiptoZipCode": 98225
    },
    {
        "OrderNumber": 11321092,
        "CustomerNumber": 168358,
        "CustomerName": "SAMISH COMMONS",
        "StockShipped": "*DELIVERY",
        "Description1": "DELIVERY CHARGE",
        "QuantitytoShip": 1,
        "Salesperson": 301,
        "ShippingDate": 45278,
        "ShiptoAddress1": "1000 OTIS ST #A-102",
        "ShiptoAddress2": "P/U KEYS AT CCM SHOP",
        "ShiptoCity": "BELLINGHAM",
        "ShiptoState": "WA",
        "ShiptoZipCode": 98225
    },
    {
        "OrderNumber": 11321092,
        "CustomerNumber": 168358,
        "CustomerName": "SAMISH COMMONS",
        "StockShipped": "*DISPOSAL",
        "Description1": "APPLIANCE UNINSTALLED AND",
        "QuantitytoShip": 1,
        "Salesperson": 301,
        "ShippingDate": 45278,
        "ShiptoAddress1": "1000 OTIS ST #A-102",
        "ShiptoAddress2": "P/U KEYS AT CCM SHOP",
        "ShiptoCity": "BELLINGHAM",
        "ShiptoState": "WA",
        "ShiptoZipCode": 98225
    },
    {
        "OrderNumber": 11321093,
        "CustomerNumber": 1366,
        "CustomerName": "WINDERMERE MANAGEMENT",
        "StockShipped": "WFC315S0JW",
        "Description1": "\"Whirlpool 30\\\" Freestanding\",1,301,45278,\"2166 EASTVIEW PL #6\",\"\",\"FERNDALE\",\"WA\",\"98248\",\"RAN\",45\n11321093,1366,\"WINDERMERE MANAGEMENT\",\"*DELIVERY\",\"DELIVERY CHARGE\",1,301,45278,\"2166 EASTVIEW PL #6\",\"\",\"FERNDALE\",\"WA\",\"98248\",\"\",\"\"\n11321093,1366,\"WINDERMERE MANAGEMENT\",\"*DISPOSAL\",\"APPLIANCE UNINSTALLED AND\",1,301,45278,\"2166 EASTVIEW PL #6\",\"\",\"FERNDALE\",\"WA\",\"98248\",\"\",\"\"\n11321113,24130,\"BOBBINK",
        "QuantitytoShip": " BRADY & SHIRLEY\"",
        "Salesperson": "JB645DKWW",
        "ShippingDate": "\"GE 30\\\" 5.3 cu ft Electric\",1,301,45278,\"1720 JAMES ST\",\"\",\"BELLINGHAM\",\"WA\",\"98225\",\"\",\"\"\n11321113,24130,\"BOBBINK",
        "ShiptoAddress1": " BRADY & SHIRLEY\"",
        "ShiptoAddress2": "*DELIVERY",
        "ShiptoCity": "DELIVERY CHARGE",
        "ShiptoState": 1,
        "ShiptoZipCode": 301,
        "Category": 45278,
        "ServiceTime": "1720 JAMES ST",
        "__EMPTY_1": "BELLINGHAM",
        "__EMPTY_2": "WA",
        "__EMPTY_3": 98225
    },
    {
        "OrderNumber": 11321113,
        "CustomerNumber": 24130,
        "CustomerName": "BOBBINK, BRADY & SHIRLEY",
        "StockShipped": "*CORD",
        "Description1": "RANGE OR DRYER CORD",
        "QuantitytoShip": 1,
        "Salesperson": 301,
        "ShippingDate": 45278,
        "ShiptoAddress1": "1720 JAMES ST",
        "ShiptoCity": "BELLINGHAM",
        "ShiptoState": "WA",
        "ShiptoZipCode": 98225
    },
    {
        "OrderNumber": 11321113,
        "CustomerNumber": 24130,
        "CustomerName": "BOBBINK, BRADY & SHIRLEY",
        "StockShipped": "*DISPOSAL",
        "Description1": "APPLIANCE UNINSTALLED AND",
        "QuantitytoShip": 1,
        "Salesperson": 301,
        "ShippingDate": 45278,
        "ShiptoAddress1": "1720 JAMES ST",
        "ShiptoCity": "BELLINGHAM",
        "ShiptoState": "WA",
        "ShiptoZipCode": 98225
    },
    {
        "OrderNumber": 11321124,
        "CustomerNumber": 60310,
        "CustomerName": "SHEEHAN, TODD",
        "StockShipped": "WM8900HBA",
        "Description1": "\"LG 29\\\" Front Load Washer\",1,301,45278,\"1730 N STATE ST\",\"\",\"BELLINGHAM\",\"WA\",\"98225\",\"WAS\",30\n11321124,60310,\"SHEEHAN",
        "QuantitytoShip": " TODD\"",
        "Salesperson": "*DELIVERY",
        "ShippingDate": "DELIVERY CHARGE",
        "ShiptoAddress1": 1,
        "ShiptoAddress2": 301,
        "ShiptoCity": 45278,
        "ShiptoState": "1730 N STATE ST",
        "Category": "BELLINGHAM",
        "ServiceTime": "WA",
        "__EMPTY": 98225
    },
    {
        "OrderNumber": 11321124,
        "CustomerNumber": 60310,
        "CustomerName": "SHEEHAN, TODD",
        "StockShipped": "*HOSE-REGULAR",
        "Description1": "ONE PAIR REGULAR HOSES",
        "QuantitytoShip": 1,
        "Salesperson": 301,
        "ShippingDate": 45278,
        "ShiptoAddress1": "1730 N STATE ST",
        "ShiptoCity": "BELLINGHAM",
        "ShiptoState": "WA",
        "ShiptoZipCode": 98225
    },
    {
        "OrderNumber": 11321124,
        "CustomerNumber": 60310,
        "CustomerName": "SHEEHAN, TODD",
        "StockShipped": "*DISPOSAL",
        "Description1": "APPLIANCE UNINSTALLED AND",
        "QuantitytoShip": 1,
        "Salesperson": 301,
        "ShippingDate": 45278,
        "ShiptoAddress1": "1730 N STATE ST",
        "ShiptoCity": "BELLINGHAM",
        "ShiptoState": "WA",
        "ShiptoZipCode": 98225
    },
    {
        "OrderNumber": 11321131,
        "CustomerNumber": 44450,
        "CustomerName": "BELLEAU WOODS APTS",
        "StockShipped": "HTX24EASKWS",
        "Description1": "\"Hotpoint 27\\\" 6.2 cu ft\",1,301,45278,\"4002 NORTHWEST AVE #109\",\"\",\"BELLINGHAM\",\"WA\",\"98226\",\"DRY\",45\n11321131,44450,\"BELLEAU WOODS APTS\",\"*DELIVERY\",\"DELIVERY CHARGE\",1,301,45278,\"4002 NORTHWEST AVE #109\",\"\",\"BELLINGHAM\",\"WA\",\"98226\",\"\",\"\"\n11321131,44450,\"BELLEAU WOODS APTS\",\"*DISPOSAL\",\"APPLIANCE UNINSTALLED AND\",1,301,45278,\"4002 NORTHWEST AVE #109\",\"\",\"BELLINGHAM\",\"WA\",\"98226\",\"\",\"\"\n6001027466,53653,\"MARMON",
        "QuantitytoShip": " STEVE & MICHELLE\"",
        "Salesperson": "LSIL6336F",
        "ShippingDate": "\"LG 30\\\" Smart Induction\",1,331,45278,\"7274 DAHLBERG RD\",\"\",\"FERNDALE\",\"WA\",\"98248\",\"\",\"\"\n6001027466,53653,\"MARMON",
        "ShiptoAddress1": " STEVE & MICHELLE\"",
        "ShiptoAddress2": "*CORD",
        "ShiptoCity": "RANGE OR DRYER CORD",
        "ShiptoState": 1,
        "ShiptoZipCode": 331,
        "Category": 45278,
        "ServiceTime": "7274 DAHLBERG RD",
        "__EMPTY_1": "FERNDALE",
        "__EMPTY_2": "WA",
        "__EMPTY_3": 98248
    },
    {
        "OrderNumber": 6001027466,
        "CustomerNumber": 53653,
        "CustomerName": "MARMON, STEVE & MICHELLE",
        "StockShipped": "SHP65CM5N",
        "Description1": "\"Bosch 24\\\" 500 Series Pocket\",1,331,45278,\"7274 DAHLBERG RD\",\"\",\"FERNDALE\",\"WA\",\"98248\",\"\",\"\"\n6001027466,53653,\"MARMON",
        "QuantitytoShip": " STEVE & MICHELLE\"",
        "Salesperson": "*INSTALLDISH",
        "ShippingDate": "BASIC DW INSTALL - HOOK UP TO",
        "ShiptoAddress1": 1,
        "ShiptoAddress2": 331,
        "ShiptoCity": 45278,
        "ShiptoState": "7274 DAHLBERG RD",
        "Category": "FERNDALE",
        "ServiceTime": "WA",
        "__EMPTY": 98248
    },
    {
        "OrderNumber": 6001027466,
        "CustomerNumber": 53653,
        "CustomerName": "MARMON, STEVE & MICHELLE",
        "StockShipped": "WKEX200HWA",
        "Description1": "\"LG 27\\\" Smart Electric Single\",1,331,45278,\"7274 DAHLBERG RD\",\"\",\"FERNDALE\",\"WA\",\"98248\",\"WAS\",\"\"\n6001027466,53653,\"MARMON",
        "QuantitytoShip": " STEVE & MICHELLE\"",
        "Salesperson": "*SIDEVENTL",
        "ShippingDate": "FROM FRONT SIDE VENT TO LEFT",
        "ShiptoAddress1": 1,
        "ShiptoAddress2": 331,
        "ShiptoCity": 45278,
        "ShiptoState": "7274 DAHLBERG RD",
        "Category": "FERNDALE",
        "ServiceTime": "WA",
        "__EMPTY": 98248
    },
    {
        "OrderNumber": 6001027466,
        "CustomerNumber": 53653,
        "CustomerName": "MARMON, STEVE & MICHELLE",
        "StockShipped": "*HOSE-STAINLESS",
        "Description1": "ONE PAIR STAINLESS HOSES",
        "QuantitytoShip": 1,
        "Salesperson": 331,
        "ShippingDate": 45278,
        "ShiptoAddress1": "7274 DAHLBERG RD",
        "ShiptoCity": "FERNDALE",
        "ShiptoState": "WA",
        "ShiptoZipCode": 98248
    },
    {
        "OrderNumber": 6001027466,
        "CustomerNumber": 53653,
        "CustomerName": "MARMON, STEVE & MICHELLE",
        "StockShipped": "*DRYERKIT",
        "Description1": "DRYER KIT",
        "QuantitytoShip": 1,
        "Salesperson": 331,
        "ShippingDate": 45278,
        "ShiptoAddress1": "7274 DAHLBERG RD",
        "ShiptoCity": "FERNDALE",
        "ShiptoState": "WA",
        "ShiptoZipCode": 98248
    },
    {
        "OrderNumber": 6001027466,
        "CustomerNumber": 53653,
        "CustomerName": "MARMON, STEVE & MICHELLE",
        "StockShipped": "*CORD",
        "Description1": "RANGE OR DRYER CORD",
        "QuantitytoShip": 1,
        "Salesperson": 331,
        "ShippingDate": 45278,
        "ShiptoAddress1": "7274 DAHLBERG RD",
        "ShiptoCity": "FERNDALE",
        "ShiptoState": "WA",
        "ShiptoZipCode": 98248
    },
    {
        "OrderNumber": 6001027466,
        "CustomerNumber": 53653,
        "CustomerName": "MARMON, STEVE & MICHELLE",
        "StockShipped": "*DELIVERY",
        "Description1": "DELIVERY CHARGE",
        "QuantitytoShip": 1,
        "Salesperson": 331,
        "ShippingDate": 45278,
        "ShiptoAddress1": "7274 DAHLBERG RD",
        "ShiptoCity": "FERNDALE",
        "ShiptoState": "WA",
        "ShiptoZipCode": 98248
    },
    {
        "OrderNumber": 6001027466,
        "CustomerNumber": 53653,
        "CustomerName": "MARMON, STEVE & MICHELLE",
        "StockShipped": "*INSTALLMWDRWR",
        "Description1": "INSTALL MW DRAWER",
        "QuantitytoShip": 1,
        "Salesperson": 331,
        "ShippingDate": 45278,
        "ShiptoAddress1": "7274 DAHLBERG RD",
        "ShiptoCity": "FERNDALE",
        "ShiptoState": "WA",
        "ShiptoZipCode": 98248
    },
    {
        "OrderNumber": 6001028229,
        "CustomerNumber": 47002,
        "CustomerName": "MONAHAN, MOLLY",
        "StockShipped": "WKGX201HGA",
        "Description1": "\"LG 27\\\" Smart Gas Single\",1,334,45278,\"911 41ST ST\",\"\",\"BELLINGHAM\",\"WA\",\"98229\",\"\",\"\"\n6001028229,47002,\"MONAHAN",
        "QuantitytoShip": " MOLLY\"",
        "Salesperson": "014036-ST",
        "ShippingDate": "5 YEAR EXT STACK / ALL IN ON",
        "ShiptoAddress1": 1,
        "ShiptoAddress2": 334,
        "ShiptoCity": 45278,
        "ShiptoState": "911 41ST ST",
        "Category": "BELLINGHAM",
        "ServiceTime": "WA",
        "__EMPTY": 98229
    },
    {
        "OrderNumber": 6001028229,
        "CustomerNumber": 47002,
        "CustomerName": "MONAHAN, MOLLY",
        "StockShipped": "*GASHOOKUP",
        "Description1": "GAS FLEX & HOOK-UP",
        "QuantitytoShip": 1,
        "Salesperson": 334,
        "ShippingDate": 45278,
        "ShiptoAddress1": "911 41ST ST",
        "ShiptoCity": "BELLINGHAM",
        "ShiptoState": "WA",
        "ShiptoZipCode": 98229
    },
    {
        "OrderNumber": 6001028229,
        "CustomerNumber": 47002,
        "CustomerName": "MONAHAN, MOLLY",
        "StockShipped": "*HOSE-STEAM/SS",
        "Description1": "Steam Washer and Dryer Set",
        "QuantitytoShip": 1,
        "Salesperson": 334,
        "ShippingDate": 45278,
        "ShiptoAddress1": "911 41ST ST",
        "ShiptoCity": "BELLINGHAM",
        "ShiptoState": "WA",
        "ShiptoZipCode": 98229
    },
    {
        "OrderNumber": 6001028229,
        "CustomerNumber": 47002,
        "CustomerName": "MONAHAN, MOLLY",
        "StockShipped": "*DRYERKIT",
        "Description1": "DRYER KIT",
        "QuantitytoShip": 1,
        "Salesperson": 334,
        "ShippingDate": 45278,
        "ShiptoAddress1": "911 41ST ST",
        "ShiptoCity": "BELLINGHAM",
        "ShiptoState": "WA",
        "ShiptoZipCode": 98229
    },
    {
        "OrderNumber": 6001028229,
        "CustomerNumber": 47002,
        "CustomerName": "MONAHAN, MOLLY",
        "StockShipped": "*DELIVERY",
        "Description1": "DELIVERY CHARGE",
        "QuantitytoShip": 1,
        "Salesperson": 334,
        "ShippingDate": 45278,
        "ShiptoAddress1": "911 41ST ST",
        "ShiptoCity": "BELLINGHAM",
        "ShiptoState": "WA",
        "ShiptoZipCode": 98229
    },
    {
        "OrderNumber": 6001028229,
        "CustomerNumber": 47002,
        "CustomerName": "MONAHAN, MOLLY",
        "StockShipped": "TXD160WP",
        "Description1": "\"Miele 24\\\" Heat Pump Dryer\",-1,334,45278,\"911 41ST ST\",\"\",\"BELLINGHAM\",\"WA\",\"98229\",\"DRY\",45\n6001028229,47002,\"MONAHAN",
        "QuantitytoShip": " MOLLY\"",
        "Salesperson": "*RESTOCK",
        "ShippingDate": "RESTOCK FEE FOR RETURNED ITEM",
        "ShiptoAddress1": 1,
        "ShiptoAddress2": 334,
        "ShiptoCity": 45278,
        "ShiptoState": "911 41ST ST",
        "Category": "BELLINGHAM",
        "ServiceTime": "WA",
        "__EMPTY": 98229
    },
    {
        "OrderNumber": 6001028229,
        "CustomerNumber": 47002,
        "CustomerName": "MONAHAN, MOLLY",
        "StockShipped": "WTV512",
        "Description1": "Miele Stack Kit",
        "QuantitytoShip": -1,
        "Salesperson": 334,
        "ShippingDate": 45278,
        "ShiptoAddress1": "911 41ST ST",
        "ShiptoCity": "BELLINGHAM",
        "ShiptoState": "WA",
        "ShiptoZipCode": 98229
    },
    {
        "OrderNumber": 6001028229,
        "CustomerNumber": 47002,
        "CustomerName": "MONAHAN, MOLLY",
        "StockShipped": "*RESTOCK",
        "Description1": "RESTOCK FEE FOR RETURNED ITEM",
        "QuantitytoShip": 1,
        "Salesperson": 334,
        "ShippingDate": 45278,
        "ShiptoAddress1": "911 41ST ST",
        "ShiptoCity": "BELLINGHAM",
        "ShiptoState": "WA",
        "ShiptoZipCode": 98229
    },
    {
        "OrderNumber": 6001028229,
        "CustomerNumber": 47002,
        "CustomerName": "MONAHAN, MOLLY",
        "StockShipped": "WXD160WCS",
        "Description1": "\"Miele 24\\\" Front Load Washer\",-1,334,45278,\"911 41ST ST\",\"\",\"BELLINGHAM\",\"WA\",\"98229\",\"WAS\",\"\"\n6001028229,47002,\"MONAHAN",
        "QuantitytoShip": " MOLLY\"",
        "Salesperson": "*RESTOCK",
        "ShippingDate": "RESTOCK FEE FOR RETURNED ITEM",
        "ShiptoAddress1": 1,
        "ShiptoAddress2": 334,
        "ShiptoCity": 45278,
        "ShiptoState": "911 41ST ST",
        "Category": "BELLINGHAM",
        "ServiceTime": "WA",
        "__EMPTY": 98229
    },
    {
        "OrderNumber": 6001028428,
        "CustomerNumber": 83361,
        "CustomerName": "EDWARDS, CHRISTOPHER",
        "StockShipped": "*ESP",
        "Description1": "CUSTOMER DECLINED EXT WARRANTY",
        "QuantitytoShip": 1,
        "Salesperson": 360,
        "ShippingDate": 45278,
        "ShiptoAddress1": "24 JASPER RIDGE LN.",
        "ShiptoCity": "BELLINGHAM",
        "ShiptoState": "WA",
        "ShiptoZipCode": 98229
    },
    {
        "OrderNumber": 6001028428,
        "CustomerNumber": 83361,
        "CustomerName": "EDWARDS, CHRISTOPHER",
        "StockShipped": "WDT730HAMZ",
        "Description1": "\"Whirlpool 24\\\" Fully Integrated\",1,360,45278,\"24 JASPER RIDGE LN.\",\"\",\"BELLINGHAM\",\"WA\",\"98229\",\"DIS\",\"\"\n6001028428,83361,\"EDWARDS",
        "QuantitytoShip": " CHRISTOPHER\"",
        "Salesperson": "*DELIVERY",
        "ShippingDate": "DELIVERY CHARGE",
        "ShiptoAddress1": 1,
        "ShiptoAddress2": 360,
        "ShiptoCity": 45278,
        "ShiptoState": "24 JASPER RIDGE LN.",
        "Category": "BELLINGHAM",
        "ServiceTime": "WA",
        "__EMPTY": 98229
    },
    {
        "OrderNumber": 6001028428,
        "CustomerNumber": 83361,
        "CustomerName": "EDWARDS, CHRISTOPHER",
        "StockShipped": "*DISPOSAL",
        "Description1": "APPLIANCE UNINSTALLED AND",
        "QuantitytoShip": 1,
        "Salesperson": 360,
        "ShippingDate": 45278,
        "ShiptoAddress1": "24 JASPER RIDGE LN.",
        "ShiptoCity": "BELLINGHAM",
        "ShiptoState": "WA",
        "ShiptoZipCode": 98229
    },
    {
        "OrderNumber": 6001028432,
        "CustomerNumber": 186376,
        "CustomerName": "PARKS, MORGAN",
        "StockShipped": "*ESP",
        "Description1": "CUSTOMER DECLINED EXT WARRANTY",
        "QuantitytoShip": 1,
        "Salesperson": 332,
        "ShippingDate": 45278,
        "ShiptoAddress1": "135 EAST SHARRON AVE.",
        "ShiptoCity": "BURLINGTON",
        "ShiptoState": "WA",
        "ShiptoZipCode": 98233
    },
    {
        "OrderNumber": 6001028432,
        "CustomerNumber": 186376,
        "CustomerName": "PARKS, MORGAN",
        "StockShipped": "WRS325SDHZ",
        "Description1": "\"Whirlpool 36\\\" Side by Side\",1,332,45278,\"135 EAST SHARRON AVE.\",\"\",\"BURLINGTON\",\"WA\",\"98233\",\"REF\",60\n6001028432,186376,\"PARKS",
        "QuantitytoShip": " MORGAN\"",
        "Salesperson": "*DELIVERY",
        "ShippingDate": "DELIVERY CHARGE",
        "ShiptoAddress1": 1,
        "ShiptoAddress2": 332,
        "ShiptoCity": 45278,
        "ShiptoState": "135 EAST SHARRON AVE.",
        "Category": "BURLINGTON",
        "ServiceTime": "WA",
        "__EMPTY": 98233
    },
    {
        "OrderNumber": 6001028432,
        "CustomerNumber": 186376,
        "CustomerName": "PARKS, MORGAN",
        "StockShipped": "*HOOKUPREFRIG1",
        "Description1": "HOOKUP REFRIGERATOR",
        "QuantitytoShip": 1,
        "Salesperson": 332,
        "ShippingDate": 45278,
        "ShiptoAddress1": "135 EAST SHARRON AVE.",
        "ShiptoCity": "BURLINGTON",
        "ShiptoState": "WA",
        "ShiptoZipCode": 98233
    },
    {
        "OrderNumber": 6001028432,
        "CustomerNumber": 186376,
        "CustomerName": "PARKS, MORGAN",
        "StockShipped": "*HAULAWAY",
        "Description1": "APPL CONTAINING REFRIGERANT",
        "QuantitytoShip": 1,
        "Salesperson": 332,
        "ShippingDate": 45278,
        "ShiptoAddress1": "135 EAST SHARRON AVE.",
        "ShiptoCity": "BURLINGTON",
        "ShiptoState": "WA",
        "ShiptoZipCode": 98233
    }
]

export const oldlisttest = [
    {
        "OrderNumber": 11314787,
        "CustomerNumber": 98941,
        "CustomerName": "CASSELLA, EJ",
        "StockShipped": "*HOOKUPREFRIG1",
        "Description1": "HOOKUP REFRIGERATOR",
        "QuantitytoShip": 1,
        "Salesperson": 304,
        "ShippingDate": 45278,
        "ShiptoAddress1": "1012 E TOLEDO ST",
        "ShiptoCity": "BELLINGHAM",
        "ShiptoState": "WA",
        "ShiptoZipCode": 98229
    },
    {
        "OrderNumber": 11314787,
        "CustomerNumber": 98941,
        "CustomerName": "CASSELLA, EJ",
        "StockShipped": "B36CD50SNS",
        "Description1": "\"Bosch 500 Series 36\\\" Free\",1,304,45278,\"1012 E TOLEDO ST\",\"\",\"BELLINGHAM\",\"WA\",\"98229\",\"REF\",60\n11314787,98941,\"CASSELLA",
        "QuantitytoShip": " EJ\"",
        "Salesperson": "*DELIVERY",
        "ShippingDate": "DELIVERY CHARGE",
        "ShiptoAddress1": 1,
        "ShiptoAddress2": 304,
        "ShiptoCity": 45278,
        "ShiptoState": "1012 E TOLEDO ST",
        "Category": "BELLINGHAM",
        "ServiceTime": "WA",
        "__EMPTY": 98229
//     },
//     {
//         "OrderNumber": 11316872,
//         "CustomerNumber": 128950,
//         "CustomerName": "COLLINS, MISHA",
//         "StockShipped": "LSIS6338F",
//         "Description1": "\"LG Studio 30\\\" Slide-In\",1,312,45278,\"1425 AUSTIN ST\",\"\",\"BELLINGHAM\",\"WA\",\"98229\",\"\",\"\"\n11316872,128950,\"COLLINS",
//         "QuantitytoShip": " MISHA\"",
//         "Salesperson": 14036,
//         "ShippingDate": "5 YEAR PARTS/LABOR WARRANTY",
//         "ShiptoAddress1": 1,
//         "ShiptoAddress2": 312,
//         "ShiptoCity": 45278,
//         "ShiptoState": "1425 AUSTIN ST",
//         "Category": "BELLINGHAM",
//         "ServiceTime": "WA",
//         "__EMPTY": 98229
//     },
//     {
//         "OrderNumber": 11316872,
//         "CustomerNumber": 128950,
//         "CustomerName": "COLLINS, MISHA",
//         "StockShipped": "HBC143ESS",
//         "Description1": "\"Best 43\\\" Ceiling Mounted Range\",1,312,45278,\"1425 AUSTIN ST\",\"\",\"BELLINGHAM\",\"WA\",\"98229\",\"\",\"\"\n11316872,128950,\"COLLINS",
//         "QuantitytoShip": " MISHA\"",
//         "Salesperson": 14036,
//         "ShippingDate": "5 YEAR PARTS/LABOR WARRANTY",
//         "ShiptoAddress1": 1,
//         "ShiptoAddress2": 312,
//         "ShiptoCity": 45278,
//         "ShiptoState": "1425 AUSTIN ST",
//         "Category": "BELLINGHAM",
//         "ServiceTime": "WA",
//         "__EMPTY": 98229
//     },
//     {
//         "OrderNumber": 11316872,
//         "CustomerNumber": 128950,
//         "CustomerName": "COLLINS, MISHA",
//         "StockShipped": "ILB6",
//         "Description1": "BEST 600CFM INLINE BLOWER",
//         "QuantitytoShip": 1,
//         "Salesperson": 312,
//         "ShippingDate": 45278,
//         "ShiptoAddress1": "1425 AUSTIN ST",
//         "ShiptoCity": "BELLINGHAM",
//         "ShiptoState": "WA",
//         "ShiptoZipCode": 98229
//     },
//     {
//         "OrderNumber": 11316872,
//         "CustomerNumber": 128950,
//         "CustomerName": "COLLINS, MISHA",
//         "StockShipped": "*DELIVERY",
//         "Description1": "DELIVERY CHARGE",
//         "QuantitytoShip": 1,
//         "Salesperson": 312,
//         "ShippingDate": 45278,
//         "ShiptoAddress1": "1425 AUSTIN ST",
//         "ShiptoCity": "BELLINGHAM",
//         "ShiptoState": "WA",
//         "ShiptoZipCode": 98229
//     },
//     {
//         "OrderNumber": 11316872,
//         "CustomerNumber": 128950,
//         "CustomerName": "COLLINS, MISHA",
//         "StockShipped": "*CORD",
//         "Description1": "RANGE OR DRYER CORD",
//         "QuantitytoShip": 1,
//         "Salesperson": 312,
//         "ShippingDate": 45278,
//         "ShiptoAddress1": "1425 AUSTIN ST",
//         "ShiptoCity": "BELLINGHAM",
//         "ShiptoState": "WA",
//         "ShiptoZipCode": 98229
//     },
//     {
//         "OrderNumber": 11316872,
//         "CustomerNumber": 128950,
//         "CustomerName": "COLLINS, MISHA",
//         "StockShipped": "*DISPOSAL",
//         "Description1": "APPLIANCE UNINSTALLED AND",
//         "QuantitytoShip": 1,
//         "Salesperson": 312,
//         "ShippingDate": 45278,
//         "ShiptoAddress1": "1425 AUSTIN ST",
//         "ShiptoCity": "BELLINGHAM",
//         "ShiptoState": "WA",
//         "ShiptoZipCode": 98229
//     },
//     {
//         "OrderNumber": 11316872,
//         "CustomerNumber": 128950,
//         "CustomerName": "COLLINS, MISHA",
//         "StockShipped": "*INSTALLHLINER",
//         "Description1": "\"INSTALL HOOD LINER UP TO 36\\\"\",1,312,45278,\"1425 AUSTIN ST\",\"\",\"BELLINGHAM\",\"WA\",\"98229\",\"\",\"\"\n11316872,128950,\"COLLINS",
//         "QuantitytoShip": " MISHA\"",
//         "Salesperson": "JES1657DMWW",
//         "ShippingDate": "GE 1.6 cu ft Countertop",
//         "ShiptoAddress1": 1,
//         "ShiptoAddress2": 312,
//         "ShiptoCity": 45278,
//         "ShiptoState": "1425 AUSTIN ST",
//         "Category": "BELLINGHAM",
//         "ServiceTime": "WA",
//         "__EMPTY": 98229
//     },
//     {
//         "OrderNumber": 11316872,
//         "CustomerNumber": 128950,
//         "CustomerName": "COLLINS, MISHA",
//         "StockShipped": "*DELIVERY",
//         "Description1": "DELIVERY CHARGE",
//         "QuantitytoShip": 1,
//         "Salesperson": 312,
//         "ShippingDate": 45278,
//         "ShiptoAddress1": "1425 AUSTIN ST",
//         "ShiptoCity": "BELLINGHAM",
//         "ShiptoState": "WA",
//         "ShiptoZipCode": 98229
//     },
//     {
//         "OrderNumber": 11317412,
//         "CustomerNumber": 141943,
//         "CustomerName": "LOVE, LISA",
//         "StockShipped": "GRSC2352AF",
//         "Description1": "\"Frigidaire Gallery 36\\\" 22.3\",1,329,45278,\"5626 ELM COURT\",\"\",\"FERNDALE\",\"WA\",\"98248\",\"REF\",\"\"\n11317412,141943,\"LOVE",
//         "QuantitytoShip": " LISA\"",
//         "Salesperson": "GCFE3060BF",
//         "ShippingDate": "\"Frigidaire Gallery 30\\\"\",1,329,45278,\"5626 ELM COURT\",\"\",\"FERNDALE\",\"WA\",\"98248\",\"\",\"\"\n11317412,141943,\"LOVE",
//         "ShiptoAddress1": " LISA\"",
//         "ShiptoAddress2": "JVW5301SJSS",
//         "ShiptoCity": "\"GE 30\\\" Wall Mount Chimney\",1,329,45278,\"5626 ELM COURT\",\"\",\"FERNDALE\",\"WA\",\"98248\",\"RAH\",\"\"\n11317412,141943,\"LOVE",
//         "ShiptoState": " LISA\"",
//         "ShiptoZipCode": "GDPH4515AF",
//         "Category": "\"Frigidaire Gallery 24\\\"\",1,329,45278,\"5626 ELM COURT\",\"\",\"FERNDALE\",\"WA\",\"98248\",\"\",\"\"\n11317412,141943,\"LOVE",
//         "ServiceTime": " LISA\"",
//         "__EMPTY": "FGBC5334VS",
//         "__EMPTY_1": "Frigidaire 5.3 cu ft Built In",
//         "__EMPTY_2": 1,
//         "__EMPTY_3": 329,
//         "__EMPTY_4": 45278,
//         "__EMPTY_5": "5626 ELM COURT",
//         "__EMPTY_7": "FERNDALE",
//         "__EMPTY_8": "WA",
//         "__EMPTY_9": 98248
//     },
//     {
//         "OrderNumber": 11317412,
//         "CustomerNumber": 141943,
//         "CustomerName": "LOVE, LISA",
//         "StockShipped": "*ESP",
//         "Description1": "CUSTOMER DECLINED EXT WARRANTY",
//         "QuantitytoShip": 1,
//         "Salesperson": 329,
//         "ShippingDate": 45278,
//         "ShiptoAddress1": "5626 ELM COURT",
//         "ShiptoCity": "FERNDALE",
//         "ShiptoState": "WA",
//         "ShiptoZipCode": 98248
//     },
//     {
//         "OrderNumber": 11317412,
//         "CustomerNumber": 141943,
//         "CustomerName": "LOVE, LISA",
//         "StockShipped": "*DELIVERY",
//         "Description1": "DELIVERY CHARGE",
//         "QuantitytoShip": 1,
//         "Salesperson": 329,
//         "ShippingDate": 45278,
//         "ShiptoAddress1": "5626 ELM COURT",
//         "ShiptoCity": "FERNDALE",
//         "ShiptoState": "WA",
//         "ShiptoZipCode": 98248
//     },
//     {
//         "OrderNumber": 11320648,
//         "CustomerNumber": 60916,
//         "CustomerName": "BECK, ALICIA & RICK",
//         "StockShipped": "RF203QDUVX1",
//         "Description1": "\"Fisher Paykel Quad Door 36\\\"\",1,329,45278,\"4193 SALTSPRING DR\",\"\",\"FERNDALE\",\"WA\",\"98248\",\"REF\",60\n11320648,60916,\"BECK",
//         "QuantitytoShip": " ALICIA & RICK\"",
//         "Salesperson": 14036,
//         "ShippingDate": "5 YEAR PARTS/LABOR WARRANTY",
//         "ShiptoAddress1": 1,
//         "ShiptoAddress2": 329,
//         "ShiptoCity": 45278,
//         "ShiptoState": "4193 SALTSPRING DR",
//         "Category": "FERNDALE",
//         "ServiceTime": "WA",
//         "__EMPTY": 98248
//     },
//     {
//         "OrderNumber": 11320648,
//         "CustomerNumber": 60916,
//         "CustomerName": "BECK, ALICIA & RICK",
//         "StockShipped": "*HOOKUPREFRIG1",
//         "Description1": "HOOKUP REFRIGERATOR",
//         "QuantitytoShip": 1,
//         "Salesperson": 329,
//         "ShippingDate": 45278,
//         "ShiptoAddress1": "4193 SALTSPRING DR",
//         "ShiptoCity": "FERNDALE",
//         "ShiptoState": "WA",
//         "ShiptoZipCode": 98248
//     },
//     {
//         "OrderNumber": 11320648,
//         "CustomerNumber": 60916,
//         "CustomerName": "BECK, ALICIA & RICK",
//         "StockShipped": "*HAULAWAY",
//         "Description1": "APPL CONTAINING REFRIGERANT",
//         "QuantitytoShip": 1,
//         "Salesperson": 329,
//         "ShippingDate": 45278,
//         "ShiptoAddress1": "4193 SALTSPRING DR",
//         "ShiptoCity": "FERNDALE",
//         "ShiptoState": "WA",
//         "ShiptoZipCode": 98248
//     },
//     {
//         "OrderNumber": 11320648,
//         "CustomerNumber": 60916,
//         "CustomerName": "BECK, ALICIA & RICK",
//         "StockShipped": "*DELIVERY",
//         "Description1": "DELIVERY CHARGE",
//         "QuantitytoShip": 1,
//         "Salesperson": 329,
//         "ShippingDate": 45278,
//         "ShiptoAddress1": "4193 SALTSPRING DR",
//         "ShiptoCity": "FERNDALE",
//         "ShiptoState": "WA",
//         "ShiptoZipCode": 98248
//     },
//     {
//         "OrderNumber": 11320960,
//         "CustomerNumber": 186288,
//         "CustomerName": "TOPOR, JANUSZ",
//         "StockShipped": "*ESP",
//         "Description1": "CUSTOMER DECLINED EXT WARRANTY",
//         "QuantitytoShip": 1,
//         "Salesperson": 335,
//         "ShippingDate": 45278,
//         "ShiptoAddress1": "3965 LOOMIS TRAIL RD",
//         "ShiptoCity": "BLAINE",
//         "ShiptoState": "WA",
//         "ShiptoZipCode": 98230
//     },
//     {
//         "OrderNumber": 11320960,
//         "CustomerNumber": 186288,
//         "CustomerName": "TOPOR, JANUSZ",
//         "StockShipped": "528648-61",
//         "Description1": "Sealy Banstead Plush Tight",
//         "QuantitytoShip": 1,
//         "Salesperson": 335,
//         "ShippingDate": 45278,
//         "ShiptoAddress1": "3965 LOOMIS TRAIL RD",
//         "ShiptoCity": "BLAINE",
//         "ShiptoState": "WA",
//         "ShiptoZipCode": 98230,
//         "Category": "MAT"
//     },
//     {
//         "OrderNumber": 11320960,
//         "CustomerNumber": 186288,
//         "CustomerName": "TOPOR, JANUSZ",
//         "StockShipped": "528649-51",
//         "Description1": "Sealy Banstead Plush Pillow",
//         "QuantitytoShip": 1,
//         "Salesperson": 335,
//         "ShippingDate": 45278,
//         "ShiptoAddress1": "3965 LOOMIS TRAIL RD",
//         "ShiptoCity": "BLAINE",
//         "ShiptoState": "WA",
//         "ShiptoZipCode": 98230,
//         "Category": "MAT"
//     },
//     {
//         "OrderNumber": 11320960,
//         "CustomerNumber": 186288,
//         "CustomerName": "TOPOR, JANUSZ",
//         "StockShipped": "*FREEDELIVERY",
//         "Description1": "FREE DELIVERY TO HOME",
//         "QuantitytoShip": 1,
//         "Salesperson": 335,
//         "ShippingDate": 45278,
//         "ShiptoAddress1": "3965 LOOMIS TRAIL RD",
//         "ShiptoCity": "BLAINE",
//         "ShiptoState": "WA",
//         "ShiptoZipCode": 98230
//     },
//     {
//         "OrderNumber": 11321088,
//         "CustomerNumber": 46344,
//         "CustomerName": "BEACON MANOR APARTMENTS",
//         "StockShipped": "NED4655EW",
//         "Description1": "Amana 6.5 cu ft Dryer",
//         "QuantitytoShip": 1,
//         "Salesperson": 301,
//         "ShippingDate": 45278,
//         "ShiptoAddress1": "2308 DOUGLAS RD #301",
//         "ShiptoAddress2": "DENAI 360-441-5886",
//         "ShiptoCity": "FERNDALE",
//         "ShiptoState": "WA",
//         "ShiptoZipCode": 98248,
//         "Category": "DRY",
//         "ServiceTime": 45
//     },
//     {
//         "OrderNumber": 11321088,
//         "CustomerNumber": 46344,
//         "CustomerName": "BEACON MANOR APARTMENTS",
//         "StockShipped": "*DELIVERY",
//         "Description1": "DELIVERY CHARGE",
//         "QuantitytoShip": 1,
//         "Salesperson": 301,
//         "ShippingDate": 45278,
//         "ShiptoAddress1": "2308 DOUGLAS RD #301",
//         "ShiptoAddress2": "DENAI 360-441-5886",
//         "ShiptoCity": "FERNDALE",
//         "ShiptoState": "WA",
//         "ShiptoZipCode": 98248
//     },
//     {
//         "OrderNumber": 11321088,
//         "CustomerNumber": 46344,
//         "CustomerName": "BEACON MANOR APARTMENTS",
//         "StockShipped": "*DISPOSAL",
//         "Description1": "APPLIANCE UNINSTALLED AND",
//         "QuantitytoShip": 1,
//         "Salesperson": 301,
//         "ShippingDate": 45278,
//         "ShiptoAddress1": "2308 DOUGLAS RD #301",
//         "ShiptoAddress2": "DENAI 360-441-5886",
//         "ShiptoCity": "FERNDALE",
//         "ShiptoState": "WA",
//         "ShiptoZipCode": 98248
//     },
//     {
//         "OrderNumber": 11321090,
//         "CustomerNumber": 183714,
//         "CustomerName": "CHUCKANUT PM & REALTY INC.",
//         "StockShipped": "WET4024HW",
//         "Description1": "Whirlpool 24\\\" Electric Laundry\",1,301,45278,\"2000 KNOX AVE #1\",\",\"BELLINGHAM\",\"WA\",\"98225\",\"COM\",45\n11321090,183714,\"CHUCKANUT PM & REALTY INC.\",\"*DELIVERY\",\"DELIVERY CHARGE\",1,301,45278,\"2000 KNOX AVE #1\",\",\"BELLINGHAM\",\"WA\",\"98225\",\",\"\n11321090,183714,\"CHUCKANUT PM & REALTY INC.\",\"*DISPOSAL\",\"APPLIANCE UNINSTALLED AND\",1,301,45278,\"2000 KNOX AVE #1\",\",\"BELLINGHAM\",\"WA\",\"98225\",\",\"\n11321092,168358,\"SAMISH COMMONS\",\"WM3400CW\",\"LG 27\\\" Front Load Washer",
//         "QuantitytoShip": 1,
//         "Salesperson": 301,
//         "ShippingDate": 45278,
//         "ShiptoAddress1": "1000 OTIS ST #A-102",
//         "ShiptoAddress2": "P/U KEYS AT CCM SHOP",
//         "ShiptoCity": "BELLINGHAM",
//         "ShiptoState": "WA",
//         "ShiptoZipCode": 98225,
//         "Category": "WAS",
//         "ServiceTime": 30
//     },
//     {
//         "OrderNumber": 11321092,
//         "CustomerNumber": 168358,
//         "CustomerName": "SAMISH COMMONS",
//         "StockShipped": 14035,
//         "Description1": "5 YEAR PARTS/LABOR WARRANTY",
//         "QuantitytoShip": 1,
//         "Salesperson": 301,
//         "ShippingDate": 45278,
//         "ShiptoAddress1": "1000 OTIS ST #A-102",
//         "ShiptoAddress2": "P/U KEYS AT CCM SHOP",
//         "ShiptoCity": "BELLINGHAM",
//         "ShiptoState": "WA",
//         "ShiptoZipCode": 98225
//     },
//     {
//         "OrderNumber": 11321092,
//         "CustomerNumber": 168358,
//         "CustomerName": "SAMISH COMMONS",
//         "StockShipped": "DLE3400W",
//         "Description1": "LG 27\\\" Electric Dryer\",1,301,45278,\"1000 OTIS ST #A-102\",\"P/U KEYS AT CCM SHOP\",\"BELLINGHAM\",\"WA\",\"98225\",\"DRY\",45\n11321092,168358,\"SAMISH COMMONS\",\"014035\",\"5 YEAR PARTS/LABOR WARRANTY\",1,301,45278,\"1000 OTIS ST #A-102\",\"P/U KEYS AT CCM SHOP\",\"BELLINGHAM\",\"WA\",\"98225\",\",\"\n11321092,168358,\"SAMISH COMMONS\",\"KSTK4\",\"LG Stacking Kit for 27\\\" Wide",
//         "QuantitytoShip": 1,
//         "Salesperson": 301,
//         "ShippingDate": 45278,
//         "ShiptoAddress1": "1000 OTIS ST #A-102",
//         "ShiptoAddress2": "P/U KEYS AT CCM SHOP",
//         "ShiptoCity": "BELLINGHAM",
//         "ShiptoState": "WA",
//         "ShiptoZipCode": 98225
//     },
//     {
//         "OrderNumber": 11321092,
//         "CustomerNumber": 168358,
//         "CustomerName": "SAMISH COMMONS",
//         "StockShipped": "*DELIVERY",
//         "Description1": "DELIVERY CHARGE",
//         "QuantitytoShip": 1,
//         "Salesperson": 301,
//         "ShippingDate": 45278,
//         "ShiptoAddress1": "1000 OTIS ST #A-102",
//         "ShiptoAddress2": "P/U KEYS AT CCM SHOP",
//         "ShiptoCity": "BELLINGHAM",
//         "ShiptoState": "WA",
//         "ShiptoZipCode": 98225
//     },
//     {
//         "OrderNumber": 11321092,
//         "CustomerNumber": 168358,
//         "CustomerName": "SAMISH COMMONS",
//         "StockShipped": "*DISPOSAL",
//         "Description1": "APPLIANCE UNINSTALLED AND",
//         "QuantitytoShip": 1,
//         "Salesperson": 301,
//         "ShippingDate": 45278,
//         "ShiptoAddress1": "1000 OTIS ST #A-102",
//         "ShiptoAddress2": "P/U KEYS AT CCM SHOP",
//         "ShiptoCity": "BELLINGHAM",
//         "ShiptoState": "WA",
//         "ShiptoZipCode": 98225
//     },
//     {
//         "OrderNumber": 11321093,
//         "CustomerNumber": 1366,
//         "CustomerName": "WINDERMERE MANAGEMENT",
//         "StockShipped": "WFC315S0JW",
//         "Description1": "\"Whirlpool 30\\\" Freestanding\",1,301,45278,\"2166 EASTVIEW PL #6\",\"\",\"FERNDALE\",\"WA\",\"98248\",\"RAN\",45\n11321093,1366,\"WINDERMERE MANAGEMENT\",\"*DELIVERY\",\"DELIVERY CHARGE\",1,301,45278,\"2166 EASTVIEW PL #6\",\"\",\"FERNDALE\",\"WA\",\"98248\",\"\",\"\"\n11321093,1366,\"WINDERMERE MANAGEMENT\",\"*DISPOSAL\",\"APPLIANCE UNINSTALLED AND\",1,301,45278,\"2166 EASTVIEW PL #6\",\"\",\"FERNDALE\",\"WA\",\"98248\",\"\",\"\"\n11321113,24130,\"BOBBINK",
//         "QuantitytoShip": " BRADY & SHIRLEY\"",
//         "Salesperson": "JB645DKWW",
//         "ShippingDate": "\"GE 30\\\" 5.3 cu ft Electric\",1,301,45278,\"1720 JAMES ST\",\"\",\"BELLINGHAM\",\"WA\",\"98225\",\"\",\"\"\n11321113,24130,\"BOBBINK",
//         "ShiptoAddress1": " BRADY & SHIRLEY\"",
//         "ShiptoAddress2": "*DELIVERY",
//         "ShiptoCity": "DELIVERY CHARGE",
//         "ShiptoState": 1,
//         "ShiptoZipCode": 301,
//         "Category": 45278,
//         "ServiceTime": "1720 JAMES ST",
//         "__EMPTY_1": "BELLINGHAM",
//         "__EMPTY_2": "WA",
//         "__EMPTY_3": 98225
//     },
//     {
//         "OrderNumber": 11321113,
//         "CustomerNumber": 24130,
//         "CustomerName": "BOBBINK, BRADY & SHIRLEY",
//         "StockShipped": "*CORD",
//         "Description1": "RANGE OR DRYER CORD",
//         "QuantitytoShip": 1,
//         "Salesperson": 301,
//         "ShippingDate": 45278,
//         "ShiptoAddress1": "1720 JAMES ST",
//         "ShiptoCity": "BELLINGHAM",
//         "ShiptoState": "WA",
//         "ShiptoZipCode": 98225
//     },
//     {
//         "OrderNumber": 11321113,
//         "CustomerNumber": 24130,
//         "CustomerName": "BOBBINK, BRADY & SHIRLEY",
//         "StockShipped": "*DISPOSAL",
//         "Description1": "APPLIANCE UNINSTALLED AND",
//         "QuantitytoShip": 1,
//         "Salesperson": 301,
//         "ShippingDate": 45278,
//         "ShiptoAddress1": "1720 JAMES ST",
//         "ShiptoCity": "BELLINGHAM",
//         "ShiptoState": "WA",
//         "ShiptoZipCode": 98225
//     },
//     {
//         "OrderNumber": 11321124,
//         "CustomerNumber": 60310,
//         "CustomerName": "SHEEHAN, TODD",
//         "StockShipped": "WM8900HBA",
//         "Description1": "\"LG 29\\\" Front Load Washer\",1,301,45278,\"1730 N STATE ST\",\"\",\"BELLINGHAM\",\"WA\",\"98225\",\"WAS\",30\n11321124,60310,\"SHEEHAN",
//         "QuantitytoShip": " TODD\"",
//         "Salesperson": "*DELIVERY",
//         "ShippingDate": "DELIVERY CHARGE",
//         "ShiptoAddress1": 1,
//         "ShiptoAddress2": 301,
//         "ShiptoCity": 45278,
//         "ShiptoState": "1730 N STATE ST",
//         "Category": "BELLINGHAM",
//         "ServiceTime": "WA",
//         "__EMPTY": 98225
//     },
//     {
//         "OrderNumber": 11321124,
//         "CustomerNumber": 60310,
//         "CustomerName": "SHEEHAN, TODD",
//         "StockShipped": "*HOSE-REGULAR",
//         "Description1": "ONE PAIR REGULAR HOSES",
//         "QuantitytoShip": 1,
//         "Salesperson": 301,
//         "ShippingDate": 45278,
//         "ShiptoAddress1": "1730 N STATE ST",
//         "ShiptoCity": "BELLINGHAM",
//         "ShiptoState": "WA",
//         "ShiptoZipCode": 98225
//     },
//     {
//         "OrderNumber": 11321124,
//         "CustomerNumber": 60310,
//         "CustomerName": "SHEEHAN, TODD",
//         "StockShipped": "*DISPOSAL",
//         "Description1": "APPLIANCE UNINSTALLED AND",
//         "QuantitytoShip": 1,
//         "Salesperson": 301,
//         "ShippingDate": 45278,
//         "ShiptoAddress1": "1730 N STATE ST",
//         "ShiptoCity": "BELLINGHAM",
//         "ShiptoState": "WA",
//         "ShiptoZipCode": 98225
//     },
//     {
//         "OrderNumber": 11321131,
//         "CustomerNumber": 44450,
//         "CustomerName": "BELLEAU WOODS APTS",
//         "StockShipped": "HTX24EASKWS",
//         "Description1": "\"Hotpoint 27\\\" 6.2 cu ft\",1,301,45278,\"4002 NORTHWEST AVE #109\",\"\",\"BELLINGHAM\",\"WA\",\"98226\",\"DRY\",45\n11321131,44450,\"BELLEAU WOODS APTS\",\"*DELIVERY\",\"DELIVERY CHARGE\",1,301,45278,\"4002 NORTHWEST AVE #109\",\"\",\"BELLINGHAM\",\"WA\",\"98226\",\"\",\"\"\n11321131,44450,\"BELLEAU WOODS APTS\",\"*DISPOSAL\",\"APPLIANCE UNINSTALLED AND\",1,301,45278,\"4002 NORTHWEST AVE #109\",\"\",\"BELLINGHAM\",\"WA\",\"98226\",\"\",\"\"\n6001027466,53653,\"MARMON",
//         "QuantitytoShip": " STEVE & MICHELLE\"",
//         "Salesperson": "LSIL6336F",
//         "ShippingDate": "\"LG 30\\\" Smart Induction\",1,331,45278,\"7274 DAHLBERG RD\",\"\",\"FERNDALE\",\"WA\",\"98248\",\"\",\"\"\n6001027466,53653,\"MARMON",
//         "ShiptoAddress1": " STEVE & MICHELLE\"",
//         "ShiptoAddress2": "*CORD",
//         "ShiptoCity": "RANGE OR DRYER CORD",
//         "ShiptoState": 1,
//         "ShiptoZipCode": 331,
//         "Category": 45278,
//         "ServiceTime": "7274 DAHLBERG RD",
//         "__EMPTY_1": "FERNDALE",
//         "__EMPTY_2": "WA",
//         "__EMPTY_3": 98248
//     },
//     {
//         "OrderNumber": 6001027466,
//         "CustomerNumber": 53653,
//         "CustomerName": "MARMON, STEVE & MICHELLE",
//         "StockShipped": "SHP65CM5N",
//         "Description1": "\"Bosch 24\\\" 500 Series Pocket\",1,331,45278,\"7274 DAHLBERG RD\",\"\",\"FERNDALE\",\"WA\",\"98248\",\"\",\"\"\n6001027466,53653,\"MARMON",
//         "QuantitytoShip": " STEVE & MICHELLE\"",
//         "Salesperson": "*INSTALLDISH",
//         "ShippingDate": "BASIC DW INSTALL - HOOK UP TO",
//         "ShiptoAddress1": 1,
//         "ShiptoAddress2": 331,
//         "ShiptoCity": 45278,
//         "ShiptoState": "7274 DAHLBERG RD",
//         "Category": "FERNDALE",
//         "ServiceTime": "WA",
//         "__EMPTY": 98248
//     },
//     {
//         "OrderNumber": 6001027466,
//         "CustomerNumber": 53653,
//         "CustomerName": "MARMON, STEVE & MICHELLE",
//         "StockShipped": "WKEX200HWA",
//         "Description1": "\"LG 27\\\" Smart Electric Single\",1,331,45278,\"7274 DAHLBERG RD\",\"\",\"FERNDALE\",\"WA\",\"98248\",\"WAS\",\"\"\n6001027466,53653,\"MARMON",
//         "QuantitytoShip": " STEVE & MICHELLE\"",
//         "Salesperson": "*SIDEVENTL",
//         "ShippingDate": "FROM FRONT SIDE VENT TO LEFT",
//         "ShiptoAddress1": 1,
//         "ShiptoAddress2": 331,
//         "ShiptoCity": 45278,
//         "ShiptoState": "7274 DAHLBERG RD",
//         "Category": "FERNDALE",
//         "ServiceTime": "WA",
//         "__EMPTY": 98248
//     },
//     {
//         "OrderNumber": 6001027466,
//         "CustomerNumber": 53653,
//         "CustomerName": "MARMON, STEVE & MICHELLE",
//         "StockShipped": "*HOSE-STAINLESS",
//         "Description1": "ONE PAIR STAINLESS HOSES",
//         "QuantitytoShip": 1,
//         "Salesperson": 331,
//         "ShippingDate": 45278,
//         "ShiptoAddress1": "7274 DAHLBERG RD",
//         "ShiptoCity": "FERNDALE",
//         "ShiptoState": "WA",
//         "ShiptoZipCode": 98248
//     },
//     {
//         "OrderNumber": 6001027466,
//         "CustomerNumber": 53653,
//         "CustomerName": "MARMON, STEVE & MICHELLE",
//         "StockShipped": "*DRYERKIT",
//         "Description1": "DRYER KIT",
//         "QuantitytoShip": 1,
//         "Salesperson": 331,
//         "ShippingDate": 45278,
//         "ShiptoAddress1": "7274 DAHLBERG RD",
//         "ShiptoCity": "FERNDALE",
//         "ShiptoState": "WA",
//         "ShiptoZipCode": 98248
//     },
//     {
//         "OrderNumber": 6001027466,
//         "CustomerNumber": 53653,
//         "CustomerName": "MARMON, STEVE & MICHELLE",
//         "StockShipped": "*CORD",
//         "Description1": "RANGE OR DRYER CORD",
//         "QuantitytoShip": 1,
//         "Salesperson": 331,
//         "ShippingDate": 45278,
//         "ShiptoAddress1": "7274 DAHLBERG RD",
//         "ShiptoCity": "FERNDALE",
//         "ShiptoState": "WA",
//         "ShiptoZipCode": 98248
//     },
//     {
//         "OrderNumber": 6001027466,
//         "CustomerNumber": 53653,
//         "CustomerName": "MARMON, STEVE & MICHELLE",
//         "StockShipped": "*DELIVERY",
//         "Description1": "DELIVERY CHARGE",
//         "QuantitytoShip": 1,
//         "Salesperson": 331,
//         "ShippingDate": 45278,
//         "ShiptoAddress1": "7274 DAHLBERG RD",
//         "ShiptoCity": "FERNDALE",
//         "ShiptoState": "WA",
//         "ShiptoZipCode": 98248
//     },
//     {
//         "OrderNumber": 6001027466,
//         "CustomerNumber": 53653,
//         "CustomerName": "MARMON, STEVE & MICHELLE",
//         "StockShipped": "*INSTALLMWDRWR",
//         "Description1": "INSTALL MW DRAWER",
//         "QuantitytoShip": 1,
//         "Salesperson": 331,
//         "ShippingDate": 45278,
//         "ShiptoAddress1": "7274 DAHLBERG RD",
//         "ShiptoCity": "FERNDALE",
//         "ShiptoState": "WA",
//         "ShiptoZipCode": 98248
//     },
//     {
//         "OrderNumber": 6001028229,
//         "CustomerNumber": 47002,
//         "CustomerName": "MONAHAN, MOLLY",
//         "StockShipped": "WKGX201HGA",
//         "Description1": "\"LG 27\\\" Smart Gas Single\",1,334,45278,\"911 41ST ST\",\"\",\"BELLINGHAM\",\"WA\",\"98229\",\"\",\"\"\n6001028229,47002,\"MONAHAN",
//         "QuantitytoShip": " MOLLY\"",
//         "Salesperson": "014036-ST",
//         "ShippingDate": "5 YEAR EXT STACK / ALL IN ON",
//         "ShiptoAddress1": 1,
//         "ShiptoAddress2": 334,
//         "ShiptoCity": 45278,
//         "ShiptoState": "911 41ST ST",
//         "Category": "BELLINGHAM",
//         "ServiceTime": "WA",
//         "__EMPTY": 98229
//     },
//     {
//         "OrderNumber": 6001028229,
//         "CustomerNumber": 47002,
//         "CustomerName": "MONAHAN, MOLLY",
//         "StockShipped": "*GASHOOKUP",
//         "Description1": "GAS FLEX & HOOK-UP",
//         "QuantitytoShip": 1,
//         "Salesperson": 334,
//         "ShippingDate": 45278,
//         "ShiptoAddress1": "911 41ST ST",
//         "ShiptoCity": "BELLINGHAM",
//         "ShiptoState": "WA",
//         "ShiptoZipCode": 98229
//     },
//     {
//         "OrderNumber": 6001028229,
//         "CustomerNumber": 47002,
//         "CustomerName": "MONAHAN, MOLLY",
//         "StockShipped": "*HOSE-STEAM/SS",
//         "Description1": "Steam Washer and Dryer Set",
//         "QuantitytoShip": 1,
//         "Salesperson": 334,
//         "ShippingDate": 45278,
//         "ShiptoAddress1": "911 41ST ST",
//         "ShiptoCity": "BELLINGHAM",
//         "ShiptoState": "WA",
//         "ShiptoZipCode": 98229
//     },
//     {
//         "OrderNumber": 6001028229,
//         "CustomerNumber": 47002,
//         "CustomerName": "MONAHAN, MOLLY",
//         "StockShipped": "*DRYERKIT",
//         "Description1": "DRYER KIT",
//         "QuantitytoShip": 1,
//         "Salesperson": 334,
//         "ShippingDate": 45278,
//         "ShiptoAddress1": "911 41ST ST",
//         "ShiptoCity": "BELLINGHAM",
//         "ShiptoState": "WA",
//         "ShiptoZipCode": 98229
//     },
//     {
//         "OrderNumber": 6001028229,
//         "CustomerNumber": 47002,
//         "CustomerName": "MONAHAN, MOLLY",
//         "StockShipped": "*DELIVERY",
//         "Description1": "DELIVERY CHARGE",
//         "QuantitytoShip": 1,
//         "Salesperson": 334,
//         "ShippingDate": 45278,
//         "ShiptoAddress1": "911 41ST ST",
//         "ShiptoCity": "BELLINGHAM",
//         "ShiptoState": "WA",
//         "ShiptoZipCode": 98229
//     },
//     {
//         "OrderNumber": 6001028229,
//         "CustomerNumber": 47002,
//         "CustomerName": "MONAHAN, MOLLY",
//         "StockShipped": "TXD160WP",
//         "Description1": "\"Miele 24\\\" Heat Pump Dryer\",-1,334,45278,\"911 41ST ST\",\"\",\"BELLINGHAM\",\"WA\",\"98229\",\"DRY\",45\n6001028229,47002,\"MONAHAN",
//         "QuantitytoShip": " MOLLY\"",
//         "Salesperson": "*RESTOCK",
//         "ShippingDate": "RESTOCK FEE FOR RETURNED ITEM",
//         "ShiptoAddress1": 1,
//         "ShiptoAddress2": 334,
//         "ShiptoCity": 45278,
//         "ShiptoState": "911 41ST ST",
//         "Category": "BELLINGHAM",
//         "ServiceTime": "WA",
//         "__EMPTY": 98229
//     },
//     {
//         "OrderNumber": 6001028229,
//         "CustomerNumber": 47002,
//         "CustomerName": "MONAHAN, MOLLY",
//         "StockShipped": "WTV512",
//         "Description1": "Miele Stack Kit",
//         "QuantitytoShip": -1,
//         "Salesperson": 334,
//         "ShippingDate": 45278,
//         "ShiptoAddress1": "911 41ST ST",
//         "ShiptoCity": "BELLINGHAM",
//         "ShiptoState": "WA",
//         "ShiptoZipCode": 98229
//     },
//     {
//         "OrderNumber": 6001028229,
//         "CustomerNumber": 47002,
//         "CustomerName": "MONAHAN, MOLLY",
//         "StockShipped": "*RESTOCK",
//         "Description1": "RESTOCK FEE FOR RETURNED ITEM",
//         "QuantitytoShip": 1,
//         "Salesperson": 334,
//         "ShippingDate": 45278,
//         "ShiptoAddress1": "911 41ST ST",
//         "ShiptoCity": "BELLINGHAM",
//         "ShiptoState": "WA",
//         "ShiptoZipCode": 98229
//     },
//     {
//         "OrderNumber": 6001028229,
//         "CustomerNumber": 47002,
//         "CustomerName": "MONAHAN, MOLLY",
//         "StockShipped": "WXD160WCS",
//         "Description1": "\"Miele 24\\\" Front Load Washer\",-1,334,45278,\"911 41ST ST\",\"\",\"BELLINGHAM\",\"WA\",\"98229\",\"WAS\",\"\"\n6001028229,47002,\"MONAHAN",
//         "QuantitytoShip": " MOLLY\"",
//         "Salesperson": "*RESTOCK",
//         "ShippingDate": "RESTOCK FEE FOR RETURNED ITEM",
//         "ShiptoAddress1": 1,
//         "ShiptoAddress2": 334,
//         "ShiptoCity": 45278,
//         "ShiptoState": "911 41ST ST",
//         "Category": "BELLINGHAM",
//         "ServiceTime": "WA",
//         "__EMPTY": 98229
//     },
//     {
//         "OrderNumber": 6001028428,
//         "CustomerNumber": 83361,
//         "CustomerName": "EDWARDS, CHRISTOPHER",
//         "StockShipped": "*ESP",
//         "Description1": "CUSTOMER DECLINED EXT WARRANTY",
//         "QuantitytoShip": 1,
//         "Salesperson": 360,
//         "ShippingDate": 45278,
//         "ShiptoAddress1": "24 JASPER RIDGE LN.",
//         "ShiptoCity": "BELLINGHAM",
//         "ShiptoState": "WA",
//         "ShiptoZipCode": 98229
//     },
//     {
//         "OrderNumber": 6001028428,
//         "CustomerNumber": 83361,
//         "CustomerName": "EDWARDS, CHRISTOPHER",
//         "StockShipped": "WDT730HAMZ",
//         "Description1": "\"Whirlpool 24\\\" Fully Integrated\",1,360,45278,\"24 JASPER RIDGE LN.\",\"\",\"BELLINGHAM\",\"WA\",\"98229\",\"DIS\",\"\"\n6001028428,83361,\"EDWARDS",
//         "QuantitytoShip": " CHRISTOPHER\"",
//         "Salesperson": "*DELIVERY",
//         "ShippingDate": "DELIVERY CHARGE",
//         "ShiptoAddress1": 1,
//         "ShiptoAddress2": 360,
//         "ShiptoCity": 45278,
//         "ShiptoState": "24 JASPER RIDGE LN.",
//         "Category": "BELLINGHAM",
//         "ServiceTime": "WA",
//         "__EMPTY": 98229
//     },
//     {
//         "OrderNumber": 6001028428,
//         "CustomerNumber": 83361,
//         "CustomerName": "EDWARDS, CHRISTOPHER",
//         "StockShipped": "*DISPOSAL",
//         "Description1": "APPLIANCE UNINSTALLED AND",
//         "QuantitytoShip": 1,
//         "Salesperson": 360,
//         "ShippingDate": 45278,
//         "ShiptoAddress1": "24 JASPER RIDGE LN.",
//         "ShiptoCity": "BELLINGHAM",
//         "ShiptoState": "WA",
//         "ShiptoZipCode": 98229
//     },
//     {
//         "OrderNumber": 6001028432,
//         "CustomerNumber": 186376,
//         "CustomerName": "PARKS, MORGAN",
//         "StockShipped": "*ESP",
//         "Description1": "CUSTOMER DECLINED EXT WARRANTY",
//         "QuantitytoShip": 1,
//         "Salesperson": 332,
//         "ShippingDate": 45278,
//         "ShiptoAddress1": "135 EAST SHARRON AVE.",
//         "ShiptoCity": "BURLINGTON",
//         "ShiptoState": "WA",
//         "ShiptoZipCode": 98233
//     },
//     {
//         "OrderNumber": 6001028432,
//         "CustomerNumber": 186376,
//         "CustomerName": "PARKS, MORGAN",
//         "StockShipped": "WRS325SDHZ",
//         "Description1": "\"Whirlpool 36\\\" Side by Side\",1,332,45278,\"135 EAST SHARRON AVE.\",\"\",\"BURLINGTON\",\"WA\",\"98233\",\"REF\",60\n6001028432,186376,\"PARKS",
//         "QuantitytoShip": " MORGAN\"",
//         "Salesperson": "*DELIVERY",
//         "ShippingDate": "DELIVERY CHARGE",
//         "ShiptoAddress1": 1,
//         "ShiptoAddress2": 332,
//         "ShiptoCity": 45278,
//         "ShiptoState": "135 EAST SHARRON AVE.",
//         "Category": "BURLINGTON",
//         "ServiceTime": "WA",
//         "__EMPTY": 98233
//     },
//     {
//         "OrderNumber": 6001028432,
//         "CustomerNumber": 186376,
//         "CustomerName": "PARKS, MORGAN",
//         "StockShipped": "*HOOKUPREFRIG1",
//         "Description1": "HOOKUP REFRIGERATOR",
//         "QuantitytoShip": 1,
//         "Salesperson": 332,
//         "ShippingDate": 45278,
//         "ShiptoAddress1": "135 EAST SHARRON AVE.",
//         "ShiptoCity": "BURLINGTON",
//         "ShiptoState": "WA",
//         "ShiptoZipCode": 98233
//     },
//     {
//         "OrderNumber": 6001028432,
//         "CustomerNumber": 186376,
//         "CustomerName": "PARKS, MORGAN",
//         "StockShipped": "*HAULAWAY",
//         "Description1": "APPL CONTAINING REFRIGERANT",
//         "QuantitytoShip": 1,
//         "Salesperson": 332,
//         "ShippingDate": 45278,
//         "ShiptoAddress1": "135 EAST SHARRON AVE.",
//         "ShiptoCity": "BURLINGTON",
//         "ShiptoState": "WA",
//         "ShiptoZipCode": 98233
    }
]