export const PaperlessFirstStop = [
    {
        "OrderNumber": "CHECKOFF-1",
        "CustomerName": "CHECK OFF",
        "StockShipped": "CHECK OFF",
        "Description1": "TRUCK CHECK OFF PICTURES",
        "ShippingDate": 45364,
        "QuantitytoShip": 1,
        "Location": "001EXTRA",
        "ShiptoAddress1": "4212 HANNEGAN RD",
        "ShiptoCity": "BELLINGHAM",
        "ShiptoState": "WA",
        "ShiptoZipCode": "98226"
    },
    {
        "OrderNumber": "CHECKOFF-2",
        "CustomerName": "CHECK OFF",
        "StockShipped": "CHECK OFF",
        "Description1": "TRUCK CHECK OFF PICTURES",
        "ShippingDate": 45364,
        "QuantitytoShip": 1,
        "Location": "001EXTRA",
        "ShiptoAddress1": "4175 HENNEGAN RD",
        "ShiptoCity": "BELLINGHAM",
        "ShiptoState": "WA",
        "ShiptoZipCode": "98226"
    },
    {
        "OrderNumber": "CHECKOFF-3",
        "CustomerName": "CHECK OFF",
        "StockShipped": "CHECK OFF",
        "Description1": "TRUCK CHECK OFF PICTURES",
        "ShippingDate": 45364,
        "QuantitytoShip": 1,
        "Location": "001EXTRA",
        "ShiptoAddress1": "4124 HANNEGAN RD",
        "ShiptoCity": "BELLINGHAM",
        "ShiptoState": "WA",
        "ShiptoZipCode": "98226"
    },
    {
        "OrderNumber": "CHECKOFF-4",
        "CustomerName": "CHECK OFF",
        "StockShipped": "CHECK OFF",
        "Description1": "TRUCK CHECK OFF PICTURES",
        "ShippingDate": 45364,
        "QuantitytoShip": 1,
        "Location": "001EXTRA",
        "ShiptoAddress1": "4116 HANNEGAN RD",
        "ShiptoCity": "BELLINGHAM",
        "ShiptoState": "WA",
        "ShiptoZipCode": "98226"
    },
    {
        "OrderNumber": "CHECKOFF-5",
        "CustomerName": "CHECK OFF",
        "StockShipped": "CHECK OFF",
        "Description1": "TRUCK CHECK OFF PICTURES",
        "ShippingDate": 45364,
        "QuantitytoShip": 1,
        "Location": "001EXTRA",
        "ShiptoAddress1": "2436 E BAKERVIEW RD",
        "ShiptoCity": "BELLINGHAM",
        "ShiptoState": "WA",
        "ShiptoZipCode": "98226"
    },
    {
        "OrderNumber": "CHECKOFF-6",
        "CustomerName": "CHECK OFF",
        "StockShipped": "CHECK OFF",
        "Description1": "TRUCK CHECK OFF PICTURES",
        "ShippingDate": 45364,
        "QuantitytoShip": 1,
        "Location": "001EXTRA",
        "ShiptoAddress1": "2429 E BAKER VIEW RD",
        "ShiptoCity": "BELLINGHAM",
        "ShiptoState": "WA",
        "ShiptoZipCode": "98226"
    },
    {
        "OrderNumber": "CHECKOFF-7",
        "CustomerName": "CHECK OFF",
        "StockShipped": "CHECK OFF",
        "Description1": "TRUCK CHECK OFF PICTURES",
        "ShippingDate": 45364,
        "QuantitytoShip": 1,
        "Location": "001EXTRA",
        "ShiptoAddress1": "4107 STRIDER LOOP RD STRIDER LOOP RD",
        "ShiptoCity": "BELLINGHAM",
        "ShiptoState": "WA",
        "ShiptoZipCode": "98226"
    },
    {
        "OrderNumber": "CHECKOFF-8",
        "CustomerName": "CHECK OFF",
        "StockShipped": "CHECK OFF",
        "Description1": "TRUCK CHECK OFF PICTURES",
        "ShippingDate": 45364,
        "QuantitytoShip": 1,
        "Location": "001EXTRA",
        "ShiptoAddress1": "2435 STRIDER LOOP RD",
        "ShiptoCity": "BELLINGHAM",
        "ShiptoState": "WA",
        "ShiptoZipCode": "98226"
    }
]