export const PicksTest = 
[
    {
        "Order Number": "0011320350",
        "Customer Number": "    174608",
        "Customer Name": "TICHELMAN, ROBERT",
        "Salesperson": "301",
        "Stock # Shipped": "DLEX4200W",
        "Description 1": "LG SteamDryer 27in 7.4 cu ft",
        "Shipping Date": 45341,
        "Quantity To Ship": 1,
        "Location Number": "001",
        "______________________________": "______________________________",
        "Phone Number": "206-355-9150",
        "EMail Address": "rjbt@outlook.com",
        "Ship-to Name": "TICHELMAN, ROBERT",
        "Ship-to Address 1": "4001 MAYNE LN",
        "Ship-to Address 2": "",
        "Ship-to Address 3": "",
        "Ship-to City": "FERNDALE",
        "Ship-to State": "WA",
        "Ship-to Zip Code": "98248",
        "Header Text Expanded": "DROP OFF IN BOXES IN GARAGE. CALL FOR TIME  ^ ^WILL PAY BALANCE NEXT WEEK"
    },
    {
        "Order Number": "0011320350",
        "Customer Number": "    174608",
        "Customer Name": "TICHELMAN, ROBERT",
        "Salesperson": "301",
        "Stock # Shipped": "JFC2290REM",
        "Description 1": "JennAir 72\" Counter Depth",
        "Shipping Date": 45341,
        "Quantity To Ship": 1,
        "Location Number": "001",
        "______________________________": "______________________________",
        "Phone Number": "206-355-9150",
        "EMail Address": "rjbt@outlook.com",
        "Ship-to Name": "TICHELMAN, ROBERT",
        "Ship-to Address 1": "4001 MAYNE LN",
        "Ship-to Address 2": "",
        "Ship-to Address 3": "",
        "Ship-to City": "FERNDALE",
        "Ship-to State": "WA",
        "Ship-to Zip Code": "98248",
        "Header Text Expanded": "DROP OFF IN BOXES IN GARAGE. CALL FOR TIME  ^ ^WILL PAY BALANCE NEXT WEEK"
    },
    {
        "Order Number": "0011320350",
        "Customer Number": "    174608",
        "Customer Name": "TICHELMAN, ROBERT",
        "Salesperson": "301",
        "Stock # Shipped": "KDFM404KPS",
        "Description 1": "KitchenAid 24\" Front Control",
        "Shipping Date": 45341,
        "Quantity To Ship": 1,
        "Location Number": "001",
        "______________________________": "______________________________",
        "Phone Number": "206-355-9150",
        "EMail Address": "rjbt@outlook.com",
        "Ship-to Name": "TICHELMAN, ROBERT",
        "Ship-to Address 1": "4001 MAYNE LN",
        "Ship-to Address 2": "",
        "Ship-to Address 3": "",
        "Ship-to City": "FERNDALE",
        "Ship-to State": "WA",
        "Ship-to Zip Code": "98248",
        "Header Text Expanded": "DROP OFF IN BOXES IN GARAGE. CALL FOR TIME  ^ ^WILL PAY BALANCE NEXT WEEK"
    },
    {
        "Order Number": "0011320350",
        "Customer Number": "    174608",
        "Customer Name": "TICHELMAN, ROBERT",
        "Salesperson": "301",
        "Stock # Shipped": "LWC3063ST",
        "Description 1": "LG 30\" Combination Wall Oven",
        "Shipping Date": 45341,
        "Quantity To Ship": 1,
        "Location Number": "001",
        "______________________________": "______________________________",
        "Phone Number": "206-355-9150",
        "EMail Address": "rjbt@outlook.com",
        "Ship-to Name": "TICHELMAN, ROBERT",
        "Ship-to Address 1": "4001 MAYNE LN",
        "Ship-to Address 2": "",
        "Ship-to Address 3": "",
        "Ship-to City": "FERNDALE",
        "Ship-to State": "WA",
        "Ship-to Zip Code": "98248",
        "Header Text Expanded": "DROP OFF IN BOXES IN GARAGE. CALL FOR TIME  ^ ^WILL PAY BALANCE NEXT WEEK"
    },
    {
        "Order Number": "0011320350",
        "Customer Number": "    174608",
        "Customer Name": "TICHELMAN, ROBERT",
        "Salesperson": "301",
        "Stock # Shipped": "NOPR36SSV",
        "Description 1": "Faber Pro Style Wall Mount",
        "Shipping Date": 45341,
        "Quantity To Ship": 1,
        "Location Number": "001",
        "______________________________": "______________________________",
        "Phone Number": "206-355-9150",
        "EMail Address": "rjbt@outlook.com",
        "Ship-to Name": "TICHELMAN, ROBERT",
        "Ship-to Address 1": "4001 MAYNE LN",
        "Ship-to Address 2": "",
        "Ship-to Address 3": "",
        "Ship-to City": "FERNDALE",
        "Ship-to State": "WA",
        "Ship-to Zip Code": "98248",
        "Header Text Expanded": "DROP OFF IN BOXES IN GARAGE. CALL FOR TIME  ^ ^WILL PAY BALANCE NEXT WEEK"
    },
    {
        "Order Number": "0011320350",
        "Customer Number": "    174608",
        "Customer Name": "TICHELMAN, ROBERT",
        "Salesperson": "301",
        "Stock # Shipped": "WM4200HWA",
        "Description 1": "LG TurboWash 27\" 5.0 cu ft",
        "Shipping Date": 45341,
        "Quantity To Ship": 1,
        "Location Number": "001",
        "______________________________": "______________________________",
        "Phone Number": "206-355-9150",
        "EMail Address": "rjbt@outlook.com",
        "Ship-to Name": "TICHELMAN, ROBERT",
        "Ship-to Address 1": "4001 MAYNE LN",
        "Ship-to Address 2": "",
        "Ship-to Address 3": "",
        "Ship-to City": "FERNDALE",
        "Ship-to State": "WA",
        "Ship-to Zip Code": "98248",
        "Header Text Expanded": "DROP OFF IN BOXES IN GARAGE. CALL FOR TIME  ^ ^WILL PAY BALANCE NEXT WEEK"
    },
    {
        "Order Number": "0011320350",
        "Customer Number": "    174608",
        "Customer Name": "TICHELMAN, ROBERT",
        "Salesperson": "301",
        "Stock # Shipped": "WUB50X24HZ",
        "Description 1": "Whirlpool 24\" Undercounter",
        "Shipping Date": 45341,
        "Quantity To Ship": 1,
        "Location Number": "300",
        "______________________________": "______________________________",
        "Phone Number": "206-355-9150",
        "EMail Address": "rjbt@outlook.com",
        "Ship-to Name": "TICHELMAN, ROBERT",
        "Ship-to Address 1": "4001 MAYNE LN",
        "Ship-to Address 2": "",
        "Ship-to Address 3": "",
        "Ship-to City": "FERNDALE",
        "Ship-to State": "WA",
        "Ship-to Zip Code": "98248",
        "Header Text Expanded": "DROP OFF IN BOXES IN GARAGE. CALL FOR TIME  ^ ^WILL PAY BALANCE NEXT WEEK"
    },
    {
        "Order Number": "0011322192",
        "Customer Number": "    187216",
        "Customer Name": "CLINE, THOMAS",
        "Salesperson": "301",
        "Stock # Shipped": "LRFCS25D3S",
        "Description 1": "LG 33\" 25 CU Ft 3-Door",
        "Shipping Date": 45341,
        "Quantity To Ship": 1,
        "Location Number": "001",
        "______________________________": "______________________________",
        "Phone Number": "206-271-4562",
        "EMail Address": "+",
        "Ship-to Name": "CLINE, THOMAS",
        "Ship-to Address 1": "1531 VALHALLA ST",
        "Ship-to Address 2": "",
        "Ship-to Address 3": "",
        "Ship-to City": "BELLINGHAM",
        "Ship-to State": "WA",
        "Ship-to Zip Code": "98226",
        "Header Text Expanded": "DELIVER & SET UP NEW REFER. CALL FOR TIME. MOVE OLD TO GARAGE PUT IN PLACE WHILE THEY REMODEL"
    },
    {
        "Order Number": "0011322686",
        "Customer Number": "     18609",
        "Customer Name": "OPTIMUS PROPERTY SOLUTIONS",
        "Salesperson": "301",
        "Stock # Shipped": "JB645DKWW",
        "Description 1": "GE 30\" 5.3 cu ft Electric",
        "Shipping Date": 45341,
        "Quantity To Ship": 1,
        "Location Number": "001",
        "______________________________": "______________________________",
        "Phone Number": "360-657-2262",
        "EMail Address": "SUZZANNE@OPTIMUSPS.NET",
        "Ship-to Name": "OPTIMUS PROPERTY SOLUTIONS",
        "Ship-to Address 1": "8455 SELDER RD",
        "Ship-to Address 2": "",
        "Ship-to Address 3": "",
        "Ship-to City": "BLAINE",
        "Ship-to State": "WA",
        "Ship-to Zip Code": "98230",
        "Header Text Expanded": "INSTALL NEW RANGE, NO HAULAWAY. COUPLE STEPS ONTO PORCH. PLEASE CALL 360-657-2262 KYLE HARPER"
    },
    {
        "Order Number": "0011322767",
        "Customer Number": "      1366",
        "Customer Name": "WINDERMERE MANAGEMENT",
        "Salesperson": "301",
        "Stock # Shipped": "*COINOP",
        "Description 1": "CONVERT TO COIN-OP",
        "Shipping Date": 45341,
        "Quantity To Ship": 1,
        "Location Number": "001EXTRA",
        "______________________________": "______________________________",
        "Phone Number": "360-393-1149",
        "EMail Address": "invoices@rentalsbywindermere.com",
        "Ship-to Name": "PARKRIDGE APTS",
        "Ship-to Address 1": "1812 ALABAMA ST",
        "Ship-to Address 2": "LAUNDRY ROOM",
        "Ship-to Address 3": "",
        "Ship-to City": "BELLINGHAM",
        "Ship-to State": "WA",
        "Ship-to Zip Code": "98229",
        "Header Text Expanded": "DELIVER & SET UP NEW STACKED DRYERS. SET COIN BOX FOR $2.00PER LOAD. INSTALL AND HAUL OLD. CALL MIKE FROM EN CRISTO AT 360-393-1149. HE MUST BE PRESET AT DELIVERY TO ACCEPT COIN BOX KEYS AT USE AND CARE MANUAL AND POINT OUT WHICH STACKED DRYER TO HAUL OFF"
    },
    {
        "Order Number": "0011322767",
        "Customer Number": "      1366",
        "Customer Name": "WINDERMERE MANAGEMENT",
        "Salesperson": "301",
        "Stock # Shipped": "CSP2940HQ",
        "Description 1": "Whirlpool 27\" Commercial Stack",
        "Shipping Date": 45341,
        "Quantity To Ship": "1 COIN OP",
        "Location Number": "001",
        "______________________________": "______________________________",
        "Phone Number": "360-393-1149",
        "EMail Address": "invoices@rentalsbywindermere.com",
        "Ship-to Name": "PARKRIDGE APTS",
        "Ship-to Address 1": "1812 ALABAMA ST",
        "Ship-to Address 2": "LAUNDRY ROOM",
        "Ship-to Address 3": "",
        "Ship-to City": "BELLINGHAM",
        "Ship-to State": "WA",
        "Ship-to Zip Code": "98229",
        "Header Text Expanded": "DELIVER & SET UP NEW STACKED DRYERS. SET COIN BOX FOR $2.00PER LOAD. INSTALL AND HAUL OLD. CALL MIKE FROM EN CRISTO AT 360-393-1149. HE MUST BE PRESET AT DELIVERY TO ACCEPT COIN BOX KEYS AT USE AND CARE MANUAL AND POINT OUT WHICH STACKED DRYER TO HAUL OFF"
    },
    {
        "Order Number": "0011323036",
        "Customer Number": "     20884",
        "Customer Name": "PTLA",
        "Salesperson": "301",
        "Stock # Shipped": "WFC315S0JS",
        "Description 1": "Whirlpool 30\" Freestanding",
        "Shipping Date": 45341,
        "Quantity To Ship": 1,
        "Location Number": "001",
        "______________________________": "______________________________",
        "Phone Number": "360-306-2699",
        "EMail Address": "invoices@ptlamgmt.com",
        "Ship-to Name": "PTLA",
        "Ship-to Address 1": "4316 FUSCHIA DR #202",
        "Ship-to Address 2": "CALL PAIA AT 360-306-2699",
        "Ship-to Address 3": "",
        "Ship-to City": "BELLINGHAM",
        "Ship-to State": "WA",
        "Ship-to Zip Code": "98226",
        "Header Text Expanded": "DELIVER & SET UP NEW RANGE. CALL PAIA AT 360-306-2699. INSTALL AND HAUL OLD UNIT"
    },
    {
        "Order Number": "0011323060",
        "Customer Number": "     12839",
        "Customer Name": "PADDEN CREEK APTS",
        "Salesperson": "301",
        "Stock # Shipped": "NTW4519JW",
        "Description 1": "Amana 4.4 cu ft Top Load",
        "Shipping Date": 45341,
        "Quantity To Ship": 1,
        "Location Number": "001",
        "______________________________": "______________________________",
        "Phone Number": "801-404-9248",
        "EMail Address": "paddencreek_fairhavenpark@yahoo.com",
        "Ship-to Name": "PADDEN CREEK APTS",
        "Ship-to Address 1": "1928 18TH ST #H201",
        "Ship-to Address 2": "DARRIN 801-404-9248",
        "Ship-to Address 3": "",
        "Ship-to City": "BELLINGHAM",
        "Ship-to State": "WA",
        "Ship-to Zip Code": "98225",
        "Header Text Expanded": "DELIVER & SET UP. CALL DARRIN FOR TIME AT 801-404-9248 OR FRONT OFFICE AT 360-647-6994. INSTALL AND HAUL OLD UNIT"
    },
    {
        "Order Number": "0011319023",
        "Customer Number": "     11662",
        "Customer Name": "SLUSHER HOMES & REMODELING",
        "Salesperson": "303",
        "Stock # Shipped": "DLGX7901BE",
        "Description 1": "LG TurboSteam 27\" Gas Dryer",
        "Shipping Date": 45341,
        "Quantity To Ship": 1,
        "Location Number": "001",
        "______________________________": "______________________________",
        "Phone Number": "360-961-8337",
        "EMail Address": "tslusher@comcast.net",
        "Ship-to Name": "DALE ULRICH",
        "Ship-to Address 1": "1578 KINGSWOOD CT",
        "Ship-to Address 2": "360-961-8337",
        "Ship-to Address 3": "",
        "Ship-to City": "BELLINGHAM",
        "Ship-to State": "WA",
        "Ship-to Zip Code": "98226",
        "Header Text Expanded": "DALE:  ^360-961-8337  ^ ^INSTALL THE WASHER, DRYER, ANDTHERMADOR FREESTANDING FRIDGE. ^ ^DROP OFF THE REST IN THE GARAGE FOR THE INSTALL DEPT TOCOME TO INSTALL LATER. THANKS."
    },
    {
        "Order Number": "0011319023",
        "Customer Number": "     11662",
        "Customer Name": "SLUSHER HOMES & REMODELING",
        "Salesperson": "303",
        "Stock # Shipped": "DWHD760CFP",
        "Description 1": "Thermador 24\" Sapphire",
        "Shipping Date": 45341,
        "Quantity To Ship": 1,
        "Location Number": "500",
        "______________________________": "______________________________",
        "Phone Number": "360-961-8337",
        "EMail Address": "tslusher@comcast.net",
        "Ship-to Name": "DALE ULRICH",
        "Ship-to Address 1": "1578 KINGSWOOD CT",
        "Ship-to Address 2": "360-961-8337",
        "Ship-to Address 3": "",
        "Ship-to City": "BELLINGHAM",
        "Ship-to State": "WA",
        "Ship-to Zip Code": "98226",
        "Header Text Expanded": "DALE:  ^360-961-8337  ^ ^INSTALL THE WASHER, DRYER, ANDTHERMADOR FREESTANDING FRIDGE. ^ ^DROP OFF THE REST IN THE GARAGE FOR THE INSTALL DEPT TOCOME TO INSTALL LATER. THANKS."
    },
    {
        "Order Number": "0011319023",
        "Customer Number": "     11662",
        "Customer Name": "SLUSHER HOMES & REMODELING",
        "Salesperson": "303",
        "Stock # Shipped": "GTS22KYNRFS",
        "Description 1": "GE 33\" Top Freezer",
        "Shipping Date": 45341,
        "Quantity To Ship": 1,
        "Location Number": "001",
        "______________________________": "______________________________",
        "Phone Number": "360-961-8337",
        "EMail Address": "tslusher@comcast.net",
        "Ship-to Name": "DALE ULRICH",
        "Ship-to Address 1": "1578 KINGSWOOD CT",
        "Ship-to Address 2": "360-961-8337",
        "Ship-to Address 3": "",
        "Ship-to City": "BELLINGHAM",
        "Ship-to State": "WA",
        "Ship-to Zip Code": "98226",
        "Header Text Expanded": "DALE:  ^360-961-8337  ^ ^INSTALL THE WASHER, DRYER, ANDTHERMADOR FREESTANDING FRIDGE. ^ ^DROP OFF THE REST IN THE GARAGE FOR THE INSTALL DEPT TOCOME TO INSTALL LATER. THANKS."
    },
    {
        "Order Number": "0011319023",
        "Customer Number": "     11662",
        "Customer Name": "SLUSHER HOMES & REMODELING",
        "Salesperson": "303",
        "Stock # Shipped": "PRG305WH",
        "Description 1": "Thermador Pro Harmony",
        "Shipping Date": 45341,
        "Quantity To Ship": 1,
        "Location Number": "600",
        "______________________________": "TRANSFER TO 001 TRUCK 6",
        "Phone Number": "360-961-8337",
        "EMail Address": "tslusher@comcast.net",
        "Ship-to Name": "DALE ULRICH",
        "Ship-to Address 1": "1578 KINGSWOOD CT",
        "Ship-to Address 2": "360-961-8337",
        "Ship-to Address 3": "",
        "Ship-to City": "BELLINGHAM",
        "Ship-to State": "WA",
        "Ship-to Zip Code": "98226",
        "Header Text Expanded": "DALE:  ^360-961-8337  ^ ^INSTALL THE WASHER, DRYER, ANDTHERMADOR FREESTANDING FRIDGE. ^ ^DROP OFF THE REST IN THE GARAGE FOR THE INSTALL DEPT TOCOME TO INSTALL LATER. THANKS."
    },
    {
        "Order Number": "0011319023",
        "Customer Number": "     11662",
        "Customer Name": "SLUSHER HOMES & REMODELING",
        "Salesperson": "303",
        "Stock # Shipped": "T36FT820NS",
        "Description 1": "Thermador 36\" French Door",
        "Shipping Date": 45341,
        "Quantity To Ship": 1,
        "Location Number": "500",
        "Phone Number": "360-961-8337",
        "EMail Address": "tslusher@comcast.net",
        "Ship-to Name": "DALE ULRICH",
        "Ship-to Address 1": "1578 KINGSWOOD CT",
        "Ship-to Address 2": "360-961-8337",
        "Ship-to Address 3": "",
        "Ship-to City": "BELLINGHAM",
        "Ship-to State": "WA",
        "Ship-to Zip Code": "98226",
        "Header Text Expanded": "DALE:  ^360-961-8337  ^ ^INSTALL THE WASHER, DRYER, ANDTHERMADOR FREESTANDING FRIDGE. ^ ^DROP OFF THE REST IN THE GARAGE FOR THE INSTALL DEPT TOCOME TO INSTALL LATER. THANKS."
    },
    {
        "Order Number": "0011319023",
        "Customer Number": "     11662",
        "Customer Name": "SLUSHER HOMES & REMODELING",
        "Salesperson": "303",
        "Stock # Shipped": "WT7900HBA",
        "Description 1": "LG TurboWash 27\" Top Load",
        "Shipping Date": 45341,
        "Quantity To Ship": 1,
        "Location Number": "001",
        "______________________________": "______________________________",
        "Phone Number": "360-961-8337",
        "EMail Address": "tslusher@comcast.net",
        "Ship-to Name": "DALE ULRICH",
        "Ship-to Address 1": "1578 KINGSWOOD CT",
        "Ship-to Address 2": "360-961-8337",
        "Ship-to Address 3": "",
        "Ship-to City": "BELLINGHAM",
        "Ship-to State": "WA",
        "Ship-to Zip Code": "98226",
        "Header Text Expanded": "DALE:  ^360-961-8337  ^ ^INSTALL THE WASHER, DRYER, ANDTHERMADOR FREESTANDING FRIDGE. ^ ^DROP OFF THE REST IN THE GARAGE FOR THE INSTALL DEPT TOCOME TO INSTALL LATER. THANKS."
    },
    {
        "Order Number": "0011322266",
        "Customer Number": "      1729",
        "Customer Name": "LUMMI HOUSING AUTHORITY",
        "Salesperson": "303",
        "Stock # Shipped": "NED4655EW",
        "Description 1": "Amana 6.5 cu ft Dryer",
        "Shipping Date": 45341,
        "Quantity To Ship": 2,
        "Location Number": "001",
        "______________________________": "______________________________",
        "Phone Number": "360-306-2351",
        "EMail Address": "brendac@lha-lummi.com",
        "Ship-to Name": "LUMMI HOUSING AUTHORITY",
        "Ship-to Address 1": "2845 SCHELANGEN WAY",
        "Ship-to Address 2": "",
        "Ship-to Address 3": "",
        "Ship-to City": "BELLINGHAM",
        "Ship-to State": "WA",
        "Ship-to Zip Code": "98226",
        "Header Text Expanded": "DROP OFF IN BOXES. WITH 4 PRONG CORDS. BEFORE 4:00  ^ ^CHARLIE:  ^360-306-2351"
    },
    {
        "Order Number": "0011322266",
        "Customer Number": "      1729",
        "Customer Name": "LUMMI HOUSING AUTHORITY",
        "Salesperson": "303",
        "Stock # Shipped": "NTW4519JW",
        "Description 1": "Amana 4.4 cu ft Top Load",
        "Shipping Date": 45341,
        "Quantity To Ship": 2,
        "Location Number": "001",
        "______________________________": "______________________________",
        "Phone Number": "360-306-2351",
        "EMail Address": "brendac@lha-lummi.com",
        "Ship-to Name": "LUMMI HOUSING AUTHORITY",
        "Ship-to Address 1": "2845 SCHELANGEN WAY",
        "Ship-to Address 2": "",
        "Ship-to Address 3": "",
        "Ship-to City": "BELLINGHAM",
        "Ship-to State": "WA",
        "Ship-to Zip Code": "98226",
        "Header Text Expanded": "DROP OFF IN BOXES. WITH 4 PRONG CORDS. BEFORE 4:00  ^ ^CHARLIE:  ^360-306-2351"
    },
    {
        "Order Number": "0011322266",
        "Customer Number": "      1729",
        "Customer Name": "LUMMI HOUSING AUTHORITY",
        "Salesperson": "303",
        "Stock # Shipped": "WET4027HW",
        "Description 1": "WP WASHER/DRYER COMBO",
        "Shipping Date": 45341,
        "Quantity To Ship": 2,
        "Location Number": "001",
        "______________________________": "______________________________",
        "Phone Number": "360-306-2351",
        "EMail Address": "brendac@lha-lummi.com",
        "Ship-to Name": "LUMMI HOUSING AUTHORITY",
        "Ship-to Address 1": "2845 SCHELANGEN WAY",
        "Ship-to Address 2": "",
        "Ship-to Address 3": "",
        "Ship-to City": "BELLINGHAM",
        "Ship-to State": "WA",
        "Ship-to Zip Code": "98226",
        "Header Text Expanded": "DROP OFF IN BOXES. WITH 4 PRONG CORDS. BEFORE 4:00  ^ ^CHARLIE:  ^360-306-2351"
    },
    {
        "Order Number": "0011322988",
        "Customer Number": "    151394",
        "Customer Name": "SWANSON, ASHLEY",
        "Salesperson": "303",
        "Stock # Shipped": "WET4027HW",
        "Description 1": "WP WASHER/DRYER COMBO",
        "Shipping Date": 45341,
        "Quantity To Ship": 1,
        "Location Number": "001",
        "______________________________": "______________________________",
        "Phone Number": "208-818-8357",
        "EMail Address": "+",
        "Ship-to Name": "SWANSON, ASHLEY",
        "Ship-to Address 1": "1808 TEXAS ST.",
        "Ship-to Address 2": "",
        "Ship-to Address 3": "",
        "Ship-to City": "BELLINGHAM",
        "Ship-to State": "WA",
        "Ship-to Zip Code": "98226",
        "Header Text Expanded": "CHRISTY: 208-818-8357. INSTALL& HAUL THE OLD SET. ON MAIN FLOOR."
    },
    {
        "Order Number": "0011316338",
        "Customer Number": "    182742",
        "Customer Name": "LAKE, STEVE & JENNIFER",
        "Salesperson": "304",
        "Stock # Shipped": "ELFG7437AG",
        "Description 1": "Electrolux 27\" Gas Dryer",
        "Shipping Date": 45341,
        "Quantity To Ship": 1,
        "Location Number": "001",
        "______________________________": "______________________________",
        "Phone Number": "808-357-5422",
        "EMail Address": "+",
        "Ship-to Name": "LAKE, STEVE & JENNIFER",
        "Ship-to Address 1": "1810 36TH ST",
        "Ship-to Address 2": "",
        "Ship-to Address 3": "",
        "Ship-to City": "BELLINGHAM",
        "Ship-to State": "WA",
        "Ship-to Zip Code": "98229",
        "Header Text Expanded": "** ON 2/19 DO NOT DELIVERY REFER **  ^ ^STEVE TO CPU ONE PED BEFORE INSTALL  ^ ^STEVE 808-357-5421  ^ ^ ^DELIVER AND INSTALL LAUNDRY SET AND REFER. *PEDS FOR LAUNDRY ON SITE* **PANELS FOR BESPOKE REFRIGERATOR NEED TO BE INSTALLED**  ^ ^CALL JENNIFER WITH A TIME @ 808-357-5422"
    },
    {
        "Order Number": "0011316338",
        "Customer Number": "    182742",
        "Customer Name": "LAKE, STEVE & JENNIFER",
        "Salesperson": "304",
        "Stock # Shipped": "ELFW7437AG",
        "Description 1": "Electrolux 27\" Front Load",
        "Shipping Date": 45341,
        "Quantity To Ship": 1,
        "Location Number": "001",
        "______________________________": "______________________________",
        "Phone Number": "808-357-5422",
        "EMail Address": "+",
        "Ship-to Name": "LAKE, STEVE & JENNIFER",
        "Ship-to Address 1": "1810 36TH ST",
        "Ship-to Address 2": "",
        "Ship-to Address 3": "",
        "Ship-to City": "BELLINGHAM",
        "Ship-to State": "WA",
        "Ship-to Zip Code": "98229",
        "Header Text Expanded": "** ON 2/19 DO NOT DELIVERY REFER **  ^ ^STEVE TO CPU ONE PED BEFORE INSTALL  ^ ^STEVE 808-357-5421  ^ ^ ^DELIVER AND INSTALL LAUNDRY SET AND REFER. *PEDS FOR LAUNDRY ON SITE* **PANELS FOR BESPOKE REFRIGERATOR NEED TO BE INSTALLED**  ^ ^CALL JENNIFER WITH A TIME @ 808-357-5422"
    },
    {
        "Order Number": "0011320466",
        "Customer Number": "    181464",
        "Customer Name": "PEACE HOME CONSTRUCTION LLC",
        "Salesperson": "304",
        "Stock # Shipped": "WM4000HWA",
        "Description 1": "LG 27\" Smart Front Load",
        "Shipping Date": 45341,
        "Quantity To Ship": 1,
        "Location Number": "001",
        "______________________________": "______________________________",
        "Phone Number": "702-755-5281",
        "EMail Address": "+",
        "Ship-to Name": "SURJEET GILL",
        "Ship-to Address 1": "8767 WOOD DUCK WAY",
        "Ship-to Address 2": "",
        "Ship-to Address 3": "",
        "Ship-to City": "BLAINE",
        "Ship-to State": "WA",
        "Ship-to Zip Code": "98230",
        "Header Text Expanded": "*PLEASE MAKE FIRST STOP*  ^ ^ ^HARPREET TO PICKUP RANGE CORD.INSTALL WASHER SECOND FLOOR. CALL  ^HARPREET @ 702-755-5281 WITH A TIME AND WHEN YOU ARE ON THE WAY."
    },
    {
        "Order Number": "0011322722",
        "Customer Number": "    187639",
        "Customer Name": "NEVILLE, ASHLEY",
        "Salesperson": "304",
        "Stock # Shipped": "GYE18JYLFS",
        "Description 1": "GE 33\" Counter-Depth French-",
        "Shipping Date": 45341,
        "Quantity To Ship": 1,
        "Location Number": "001",
        "______________________________": "______________________________",
        "Phone Number": "206-550-8315",
        "EMail Address": "ajmaiken@gmail.com",
        "Ship-to Name": "NEVILLE, ASHLEY",
        "Ship-to Address 1": "13 CASCADE LANE",
        "Ship-to Address 2": "",
        "Ship-to Address 3": "",
        "Ship-to City": "BELLINGHAM",
        "Ship-to State": "WA",
        "Ship-to Zip Code": "98229",
        "Header Text Expanded": "DELIVER AND INSTALL. HAUL AWAYTHE OLD MODEL."
    },
    {
        "Order Number": "0011323055",
        "Customer Number": "     13729",
        "Customer Name": "SHERMAN, MARK",
        "Salesperson": "312",
        "Stock # Shipped": "G5006SCUXXL",
        "Description 1": "Miele 24\" G5 Dishwasher",
        "Shipping Date": 45341,
        "Quantity To Ship": 1,
        "Location Number": "200",
        "______________________________": "______________________________",
        "Phone Number": "360-920-4172",
        "EMail Address": "marksherman777@gmail.com",
        "Ship-to Name": "SHERMAN, MARK",
        "Ship-to Address 1": "1470 GRANT ST",
        "Ship-to Address 2": "",
        "Ship-to Address 3": "",
        "Ship-to City": "BELLINGHAM",
        "Ship-to State": "WA",
        "Ship-to Zip Code": "98225",
        "Header Text Expanded": "DROP OFF IN THE KITCHEN. PLEASE DISPOSE OF OLD UNHOOKEDDISHWASHER.  THANKS!  :)"
    },
    {
        "Order Number": "2001070271",
        "Customer Number": "    124797",
        "Customer Name": "UNICK, VICTOR",
        "Salesperson": "326",
        "Stock # Shipped": "WKEX200HWA",
        "Description 1": "LG 27\" Smart Electric Single",
        "Shipping Date": 45341,
        "Quantity To Ship": 1,
        "Location Number": "500",
        "______________________________": "______________________________",
        "Phone Number": "360-507-5700",
        "EMail Address": "",
        "Ship-to Name": "UNICK, VICTOR",
        "Ship-to Address 1": "5349 NORTHWEST DR",
        "Ship-to Address 2": "",
        "Ship-to Address 3": "",
        "Ship-to City": "BELLINGHAM",
        "Ship-to State": "WA",
        "Ship-to Zip Code": "98226"
    },
    {
        "Order Number": "0011321786",
        "Customer Number": "    186896",
        "Customer Name": "CRAIG, ANNIKA",
        "Salesperson": "329",
        "Stock # Shipped": "CXE22DP4PW2",
        "Description 1": "GE Cafe 36\" French Door",
        "Shipping Date": 45341,
        "Quantity To Ship": 1,
        "Location Number": "001",
        "______________________________": "______________________________",
        "Phone Number": "253-241-0753",
        "EMail Address": "+",
        "Ship-to Name": "CRAIG, ANNIKA",
        "Ship-to Address 1": "14A INLET CIRCLE",
        "Ship-to Address 2": "",
        "Ship-to Address 3": "",
        "Ship-to City": "BELLINGHAM",
        "Ship-to State": "WA",
        "Ship-to Zip Code": "98229",
        "Header Text Expanded": "**CUSTOMER WILL NOT BE HOME BETWEEN 1-3PM**  ^ ^annika.craig@gmail.com  ^ ^ ^DELIVER, INSTALL, PLACE THE OLD ONE IN GARAGE. THANKS SO MUCH! STEEP DRIVEWAY. TWO STEPS UP THE FRONT PORCH INTO THE HOME. ^ ^TENTATIVE ETA FIRST WEEK OF FEBRUARY. SUBJECT TO CHANGE DUE TO SUPPLY CHAIN ISSUES."
    },
    {
        "Order Number": "6001029115",
        "Customer Number": "    187845",
        "Customer Name": "BOGUE, MEGAN",
        "Salesperson": "331",
        "Stock # Shipped": "WGD4950HW",
        "Description 1": "Whirlpool 29\" Gas Dryer",
        "Shipping Date": 45341,
        "Quantity To Ship": 1,
        "Location Number": "001",
        "______________________________": "______________________________",
        "Phone Number": "360-708-1127",
        "EMail Address": "+",
        "Ship-to Name": "BOGUE, MEGAN",
        "Ship-to Address 1": "16722 PETERSON RD",
        "Ship-to Address 2": "",
        "Ship-to Address 3": "",
        "Ship-to City": "BURLINGTON",
        "Ship-to State": "WA",
        "Ship-to Zip Code": "98233",
        "Header Text Expanded": "WE ARE GOING TO HOOK UP THE NEW UNIT, HAUL AWAY THE OLD AND DELIVER. NO STAIRS, DRIVEWAY IS EASY."
    },
    {
        "Order Number": "2001071146",
        "Customer Number": "     55433",
        "Customer Name": "EKEMA, KYLE & SWANDELL",
        "Salesperson": "336",
        "Stock # Shipped": "KDFE204KPS",
        "Description 1": "KitchenAid 24\" Front Control",
        "Shipping Date": 45341,
        "Quantity To Ship": 1,
        "Location Number": "001",
        "______________________________": "______________________________",
        "Phone Number": "360-815-1999",
        "EMail Address": "+",
        "Ship-to Name": "EKEMA, KYLE & SWANDELL",
        "Ship-to Address 1": "1405 BIRCH BAY LYNDEN RD",
        "Ship-to Address 2": "",
        "Ship-to Address 3": "",
        "Ship-to City": "FERNDALE",
        "Ship-to State": "WA",
        "Ship-to Zip Code": "98248",
        "Header Text Expanded": "PLEASE DROP OFF APPLIANCES FORKYLE TO INSTALL. NO OLDS TO HAULAWAY THANKS!"
    },
    {
        "Order Number": "2001071146",
        "Customer Number": "     55433",
        "Customer Name": "EKEMA, KYLE & SWANDELL",
        "Salesperson": "336",
        "Stock # Shipped": "MVW5035MW",
        "Description 1": "Maytag 28\" Top Load Washer",
        "Shipping Date": 45341,
        "Quantity To Ship": 1,
        "Location Number": "001",
        "______________________________": "______________________________",
        "Phone Number": "360-815-1999",
        "EMail Address": "+",
        "Ship-to Name": "EKEMA, KYLE & SWANDELL",
        "Ship-to Address 1": "1405 BIRCH BAY LYNDEN RD",
        "Ship-to Address 2": "",
        "Ship-to Address 3": "",
        "Ship-to City": "FERNDALE",
        "Ship-to State": "WA",
        "Ship-to Zip Code": "98248",
        "Header Text Expanded": "PLEASE DROP OFF APPLIANCES FORKYLE TO INSTALL. NO OLDS TO HAULAWAY THANKS!"
    },
    {
        "Order Number": "2001070917",
        "Customer Number": "54682",
        "Customer Name": "SCHRAMER, JOE AND HEIDI",
        "Salesperson": "340",
        "Stock # Shipped": "FRFG1723AV",
        "Description 1": "FRIGIDAIRE REFER",
        "Shipping Date": 45341,
        "Quantity To Ship": 1,
        "Location Number": "001",
        "______________________________": "______________________________",
        "Phone Number": "360-738-8803",
        "Ship-to Name": "JOE AND HEIDI SCHRAMER",
        "Ship-to Address 1": "7704 BIRCHBAY DR CIRCLE 3, UNIT 6",
        "Ship-to City": "BLAINE",
        "Ship-to State": "WA",
        "Ship-to Zip Code": "98230",
        "Header Text Expanded": "CALL CUST WHEN ON THE WAY. DROP OFF PRODUCTS IN HOUSE. FLAT PARKING IN FRONT OF TRAILER. CIRLCE 3 UNIT 6"
    },
    {
        "Order Number": "2001070917",
        "Customer Number": "54682",
        "Customer Name": "SCHRAMER, JOE AND HEIDI",
        "Salesperson": "340",
        "Stock # Shipped": "LSGL5833F",
        "Description 1": "LG RANGE",
        "Shipping Date": 45341,
        "Quantity To Ship": 1,
        "Location Number": "001",
        "______________________________": "______________________________",
        "Phone Number": "360-738-8803",
        "Ship-to Name": "JOE AND HEIDI SCHRAMER",
        "Ship-to Address 1": "7704 BIRCHBAY DR CIRCLE 3, UNIT 6",
        "Ship-to City": "BLAINE",
        "Ship-to State": "WA",
        "Ship-to Zip Code": "98230",
        "Header Text Expanded": "CALL CUST WHEN ON THE WAY. DROP OFF PRODUCTS IN HOUSE. FLAT PARKING IN FRONT OF TRAILER. CIRLCE 3 UNIT 6"
    },
    {
        "Order Number": "2001070917",
        "Customer Number": "54682",
        "Customer Name": "SCHRAMER, JOE AND HEIDI",
        "Salesperson": "340",
        "Stock # Shipped": "*PROPANERAN",
        "Description 1": "PROPANE CONVERSION FOR RANGES",
        "Shipping Date": 45341,
        "Quantity To Ship": 1,
        "Location Number": "001",
        "______________________________": "______________________________",
        "Phone Number": "360-738-8803",
        "Ship-to Name": "JOE AND HEIDI SCHRAMER",
        "Ship-to Address 1": "7704 BIRCHBAY DR CIRCLE 3, UNIT 6",
        "Ship-to City": "BLAINE",
        "Ship-to State": "WA",
        "Ship-to Zip Code": "98230",
        "Header Text Expanded": "CALL CUST WHEN ON THE WAY. DROP OFF PRODUCTS IN HOUSE. FLAT PARKING IN FRONT OF TRAILER. CIRLCE 3 UNIT 6"
    },
    {
        "Order Number": "2001070945-1",
        "Customer Number": "185208",
        "Customer Name": "LMJ PROPERTIES",
        "Salesperson": "340",
        "Stock # Shipped": "*DRYER FEET",
        "Description 1": "*WED8127LW FEET",
        "Shipping Date": 45341,
        "Quantity To Ship": 1,
        "Location Number": "001",
        "______________________________": "______________________________",
        "Phone Number": "206-714-8627",
        "Ship-to Name": "LMJ PROPERTIES",
        "Ship-to Address 1": "9132 THUNDERBIRD LN",
        "Ship-to City": "CONCRETE",
        "Ship-to State": "WA",
        "Ship-to Zip Code": "98237",
        "Header Text Expanded": "DRYER CAME WITHOUT FEET"
    }
]